= HƯỚNG DẪN NHẮC NHỞ TU SINH 
TRƯỞNG LÃO THÍCH THÔNG LẠC
:keywords: keywords, will, be, separated, by, commas 
:doctype: book
:sectlinks:
:icons: font


== NỘI QUY Tu viện CHƠN NHƯ

[upperroman]
. Tu sĩ và Phật tử tại Tu viện Chơn Như phải thực hiện đúng Nội quy của Tu viện và chấp hành đúng chủ trương, chính
sách của Đảng và pháp luật của Nhà nước, phải cung cấp đầy đủ các giấy tờ cần thiết trước khi vào tu học:
    - Chứng minh nhân dân/Căn cước công dân (bản gốc)
    - 01 bản Sơ yếu lý lịch (có địa phương xác nhận)
    - 03 tấm ảnh thẻ cỡ 4x6 hoặc 3x4 cm
    - Đơn phát nguyện xin đăng ký tu học (trường hợp này dùng cho những vị tu học trong thời gian dài)

. Tu sinh đến Tu viện tu tập phải chấp hành và thực hiện đúng các quy định đã được ghi rõ trong Thanh Quy Tu viện Chơn Như, cụ thể:
    1. Hãy tham khảo kinh sách và băng giảng của Trưởng Lão Thích Thông Lạc thật thông suốt trước khi đến Tu viện tu tập.
    2. Thực hiện đúng hạnh sống LỤC HÒA, 3 ĐỨC (Nhẫn nhục - Tùy thuận - Bằng lòng), 3 HẠNH (Ăn - Ngủ - Độc cư), cụ thể:
        - Ngày ăn một bữa, không được ĂN PHI THỜI.
        - Ngày được ngủ 5 giờ, gồm có trưa ngủ 1 giờ sau khi ăn; khuya được ngủ 4 giờ vào 10 giờ tối. Ngoài những giờ trên không được
        - SỐNG MỘT MÌNH, không được nói chuyện với bất kỳ một người nào (ngoại trừ những người quản lý Tu viện).

    3. Phải tu tập đúng theo đường lối của Tu viện Chơn Như là sống đúng đạo đức nhân bản - nhân quả: “Sống không làm khổ mình, khổ người và không làm khổ chúng sinh”, không được tu tập những pháp môn khác.
    4. Chấp hành nghiêm túc giờ giấc, tu tập theo thời khóa của Tu viện:
        - _Từ 02h - 05h khuya: Tu tập “xả tâm, ly dục ly ác pháp”._
        - _Từ 05h - 07h sáng: Nghỉ ngơi, vệ sinh cá nhân và khu vực sân thất._
        - _Từ 07h - 10h sáng: Tu tập “xả tâm, ly dục ly ác pháp”._
        - _Từ 10h - 14h trưa: Vệ sinh cá nhân, ăn trưa (khất thực) và ngủ trưa (1 tiếng)._
        - _Từ 14h - 17h chiều: Tu tập “xả tâm, ly dục ly ác pháp”._
        - _Từ 17h - 19h tối: Nghỉ ngơi, vệ sinh cá nhân và khu vực sân thất._
        - _Từ 19h - 22h tối: Tu tập “xả tâm, ly dục ly ác pháp”._
        - _Từ 22h - 02h đêm: Ngủ nghỉ._
    5. Để thực hiện đúng hạnh “BA Y MỘT BÁT”, tu sinh đến tu tập không nên mang theo những vật dụng cá nhân không đúng quy định vào thất như: điện thoại, máy tính, máy ghi âm, máy nghe, v.v... Trường hợp có mang theo thì phải nộp lại cho Tu viện giữ gìn trong thời gian nhập thất tu tập.

. Tu sinh vào Tu viện tu tập, nếu không chấp hành và thực hiện đúng Thanh Quy Tu viện Chơn Như sẽ được mời rời khỏi Tu viện:
    - Vi phạm lần thứ nhất được nhắc nhở.
    - Vi phạm lần thứ hai tự phát lồ sám hối.
    - Vi phạm lần thứ ba phải tự giác rời khỏi Tu viện, không được ở lại với bất kỳ lý do nào.

Trên đây là một số quy định về tu tập tại Tu viện Chơn Như. Mong rằng quý tu sinh hãy thực hiện tốt những quy định này.

[.text-center]
_Kính ghi_ +
_Tu viện Chơn Như_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== CÁCH ĐI KHẤT THỰC VÀ THỌ THỰC (ĂN CƠM)

Kính gửi quý tu sinh! Đời người tu sĩ không làm một nghề nào khác, chỉ duy nhất sống bằng nghề xin ăn ngày một bữa
mà thôi. Bởi vậy, khi khất thực và thọ thực cần phải y áo trang nghiêm chỉnh tề, để bày tỏ lòng quý trọng và sự biết ơn công sức, tịnh vật của đàn na thí chủ. Vì có những người đến Tu viện tu tập chưa biết cách thức đi khất thực và thọ thực như thế nào, nên chúng tôi tạm ghi ra hướng dẫn này để giúp mọi người cùng thực hiện cho đúng cách như sau:

=== _[.underline]#CÁCH ĐI KHẤT THỰC:#_
1. Phải mặc áo tràng (áo giới) cho nghiêm chỉnh, cổ áo phải ngay ngắn, kín đáo.
2. Tay trái đỡ dưới bát và tay phải ôm vòng bát.
3. Trước khi ra khỏi thất, đứng nghiêm chỉnh rồi tác ý: _“Xin tất cả chúng sinh hãy tránh ra, đừng nằm trên bước đường tôi đi”_.
4. Khi bước đi lưng thẳng, mắt nhìn xuống phía trước, tỉnh giác để tránh giẫm đạp lên ốc, kiến, trùn, cuốn chiếu và các côn trùng nhỏ bé khác...
5. Phải đi đường thẳng, đường lớn dẫn đến nơi khất thực, không được đi đường tắt ngang qua thất người khác.
6. Không nên đi từng bước chậm rãi như người đau bệnh, cũng không nên đi nhanh quá; nên đi bình thường, nhẹ nhàng, khoan thai.
7. Khi đến kệ cơm, đặt bát xuống, giở nắp mâm xem thức ăn để xới cơm vừa đủ ăn, và được quyền lấy những thứ như nước tương, chao, muối... đã để sẵn trên kệ cơm.
8. Lấy cơm để vào bát xong đậy nắp bát lại, nắp bát để ngửa, để những thực phẩm ngoài mâm như trái cây, bánh, hộp sữa... trên nắp bát.
9. Đặt bát cơm lên mâm thức ăn cho ngay ngắn, đứng thẳng người xá một xá biết ơn, rồi bưng bát về thất.
+
Vì tập thể khá đông, yêu cầu quý tu sinh lấy cơm nhanh gọn để kịp giờ thọ trai.

=== _[.underline]#CÁCH NGỒI ĂN VÀ CÁCH ĂN:#_
1. Đặt mâm lên bàn hoặc ngồi dưới đất, ngồi bán già hoặc kiết già giữa thất.
2. Chuẩn bị sẵn những đồ dùng như, khăn, dao, muỗng, đũa, nước uống... đầy đủ, để khi đã ngồi xuống ăn không được đứng lên đi tới đi lui, lấy thêm cái này cái kia nữa.
3. Ngồi thẳng lưng, chắp tay lên đọc bài “Ước Nguyện” cúng dường.
4. Sau khi đọc bài “Ước Nguyện” cúng dường xong, ăn ba muỗng cơm trắng và thầm nguyện.
5. Cách thức ăn: quý vị xem quyển Giới Đức Làm Người tập 1, chương 4, trang 156: “Ăn uống phải trang nghiêm tề chỉnh, có 23 giới”.
6. Thọ thực xong, chắp tay đọc bài “Biết Ơn”, rồi xá một xá.
7. Đứng lên cởi áo tràng và thu dẹp, dọn rửa. (Không nên mặc áo tràng để làm những công việc giặt rửa, lao tác...)

[.text-center]
_Kính ghi_ +
_Tu viện Chơn Như_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== ƯỚC NGUYỆN TRƯỚC KHI THỌ THỰC

Trước khi thọ thực, người tu sĩ phải ngồi xếp bằng trên ván, giường, ghế hoặc trên mặt đất, dưới bóng cây, trong chòi tranh vách lá, phải đặt bát cơm trước mặt, hai tay chắp lại, lòng thành kính dâng lên tỏ lòng biết ơn chư Phật, tổ tiên, ông bà, cha mẹ nhiều đời nhiều kiếp, và đọc lời ƯỚC NGUYỆN:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.]
_Hôm nay bữa cơm này 
Chúng con xin thành kính 
Nhớ ơn Phật Thích Ca
Tổ tiên và ông bà
Cha mẹ và quyến thuộc 
Anh em cùng bạn hữu
Nội ngoại cùng đôi bên 
Nhiều đời vô lượng kiếp 
Chúng con cũng cúi xin 
Cúng dường khắp pháp giới 
Chúng sanh và tất cả
Hữu tình và vô tình
Ðều được hưởng cơm này 
No lòng như chúng con
Ðể rồi quyết chí tu
Giải trừ tâm ác độc
Tăng trưởng hạnh từ bi 
Thương xót khắp quần sanh 
Thể hiện pháp thiền định 
Ra khỏi nhà sanh tử
Làm chủ đường luân hồi 
Báo đáp bốn trọng ân
Gìn giữ ngôi Tam Bảo
Cửu trụ mãi muôn đời_

Sau khi đọc thầm lời Ước Nguyện trước khi thọ thực, kính dâng lên lòng thành kính biết ơn của mình, người tu sĩ ăn ba miếng cơm lạt:

=== _[.underline]#TAM ĐỀ:#_
1. Miếng thứ nhất: Ước nguyện tâm con luôn ngăn ác, diệt ác; ly dục ly ác pháp, diệt ngã xả tâm;
2. Miếng thứ hai: Ước nguyện tâm con sanh thiện, tăng trưởng thiện pháp, luôn sống trong tâm bất động, thanh thản, an lạc, vô sự;
3. Miếng thứ ba: Ước nguyện tất cả chúng sanh đều ly dục, ly ác pháp, sống không làm khổ mình, khổ người.

=== _[.underline]#NGŨ QUÁN:#_
1. Quán xét công ơn người đàn na thí chủ rất nặng, làm ra thực phẩm bằng mồ hôi nước mắt, bao nhiêu công khó khổ để cúng dường.
2. Quán xét giới luật mình có nghiêm chỉnh hay chưa? Nếu còn phạm giới có xứng đáng thọ nhận sự cúng dường đó chưa?
3. Quán xét công đức tu hành ly dục, ly ác pháp của mình có xứng đáng thọ nhận sự cúng dường đó chưa?
4. Quán xét thực phẩm bất tịnh mình có nhàm chán hay chưa? Nếu đã có tâm nhàm chán thì mới xứng đáng thọ dụng của đàn na thí chủ.
5. Quán xét đời sống thiểu dục tri túc, minh hạnh của mình có tròn vẹn hay chưa? Nếu xét thấy đời sống của mình thiểu dục tri túc và oai nghi chánh hạnh đầy đủ, thì xứng đáng thọ dụng của đàn na thí chủ.

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== ƯỚC NGUYỆN SAU KHI THỌ THỰC

Sau khi thọ thực và uống nước xong, người tu sĩ chắp tay lên, thầm đọc lời ước nguyện BIẾT ƠN những đàn na thí chủ đã cúng dường tứ sự nuôi thân cho mình:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.]
_Nguyện thọ bữa cơm này 
Chúng con mãi nhớ ơn 
Người nông phu khó khổ 
Kẻ dệt cửi nhọc nhằn 
Giọt mồ hôi nước mắt 
Làm ra của cúng dường 
Người đàn na thí chủ
Vì Phật pháp trường tồn 
Chẳng nề công khó khổ 
Kính ngưỡng cúng dâng lên 
Chúng con nguyện giữ gìn 
Tiết kiệm từng chút một 
Chẳng dám phung phí phạm 
Ngày một bữa nuôi thân 
Chẳng dám ăn phi thời
Vì phi thời phí phạm
Như ăn thịt con mình
Chúng con nguyện hết sức 
Năng nổ siêng tu hành
Giải thoát thân tâm mình 
Ra khỏi nhà sanh tử
Đền đáp ơn chư Phật
Ơn sanh thành dưỡng dục 
Ơn đàn na thí chủ
Chúng con cũng nguyện cho 
Kẻ còn người đã mất
Đều được hưởng Phật pháp 
Tâm ly dục, ly ác
Không làm khổ mình, người._

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== ƯỚC NGUYỆN CỦA TÂN TỲ KHEO

Vị tỳ kheo mới xuất gia tu hành, giới luật chưa thanh tịnh, khi thọ nhận thực phẩm của đàn na thí chủ cúng dường phải
làm gì?

Khi nhận thực phẩm của đàn na thí chủ cúng dường xong, người khất sĩ phải đứng yên lặng ước nguyện:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.]
_Hôm nay con thọ nhận 
Của tín thí cúng dường 
Ước nguyện con tu tập 
Giới hạnh tròn nghiêm túc 
Không hề vi phạm lỗi 
Tâm ly dục, ly ác
Không làm khổ mình, người 
Xứng đáng đệ tử Phật 
Gương sáng cho mọi người 
Thắp lên ngọn đèn pháp 
Chấn hưng lại Phật giáo 
Con xin Phật chứng minh._

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== ĐỘC CƯ

Bắt đầu vào tu pháp môn Ngũ Căn là phải sống độc cư, nên biết ngay người tu được hay không tu được. *Vì có sống ĐỘC CƯ là tu tập được, còn không sống ĐỘC CƯ là tu tập không được.* Ở Tu viện, phần đông tu sĩ và cư sĩ đều rớt ở giai đoạn đầu tu tập phòng hộ NĂM CĂN này.

Người không đủ lòng tin dù có tu tập đúng pháp của Phật thì cũng chỉ tu tập lấy có, thường phá hạnh độc cư, đi nói chuyện người này đến người khác. Những người này hiện thân là Ma Ba Tuần trong Phật giáo, thường đi đến thất người này rồi đến thất người khác làm cho mọi người không ai tu tập được.

Khi thấy những loại Ma Ba Tuần này thì quý thầy, quý cô nên đóng cửa thất không tiếp giao, đừng ở gần, nên tránh xa, tránh xa những người này như tránh xa vi trùng bệnh truyền nhiễm.

Trong chúng chỉ có một con Ma Ba Tuần thì trong chúng đó phải cẩn thận, khi thấy bóng dáng con ma đó thì nên đóng cửa thất cho chặt và ngồi thiền nhiếp tâm bất động để vượt qua loài Ma Quỷ.
[.text-right]
(_Trích “Ba Mươi Bảy Phẩm Trợ Đạo”,_ +
_trang 21, 23-24_)

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]



== NHẮC NHỞ TU SINH +
[discrete]
=== Ngày 03-08-2011

Tu viện Chơn Như xin yêu cầu tu sinh hiện đang ở tu tập tại Khu Chuyên tu, cần thực hiện một số điều như sau:

=== _[.underline]#I- NỘI QUY:#_
1. Không trồng cây, hái rau, nấm, trái, quả, v.v...
2. Không cất giữ thức ăn trong thất (đường, muối, sữa, nước tương...).
3. Không cất giữ tiền bạc (phóng dật nhờ vả mua đồ vật linh tinh...).
4. Không dự trữ đồ vật trong thất, ví dụ 2 dép, 2 nón (mũ), xà phòng...
5. Không dùng quạt tay (mất oai nghi chánh hạnh của người tu).
6. Vào Khu Chuyên tu là đã trải qua sự rèn luyện ở Khu Tiếp nhận, nên tránh tình trạng ngồi gục tới gục lui (thiếu tỉnh thức).
7. Không được ngủ trong giờ nghỉ (sáng 5h - 7h, chiều 5h - 7h).
8. Không được ngồi thiền (đó là tư thế của thói quen ức chế từ trước).
9. Không được nhắm mắt trong giờ tu tập (dễ bị rơi vào vô ký).
10. Không ngồi trong góc, bóng tối hoặc quay mặt vô vách (khó kiểm tra).
11. Trong giờ tu tập không nên đi làm công việc khác như: đốt rác, quét sân, lau nhà, giặt đồ, đọc sách, sửa chữa, v.v...
12. Không tiếp duyên nói chuyện phá độc cư, ngoại trừ những người có trách nhiệm quản lý trong Tu viện.
13. Khi gặp khách tham quan hoặc người lạ thì nên tránh duyên, không để người xá chào hoặc xá chào lại.
14. Vào Khu Chuyên tu phải ý thức tự giác, không được gọi điện thoại, viết thư thăm hỏi, ra, vào Tu viện thăm viếng (về thăm gia đình)...
15. Trong thất và xung quanh thất phải vệ sinh sạch sẽ, gọn gàng, ngăn nắp, không được phát sinh bày biện (làm giàn, kệ, chậu, giăng mắc, treo móc...); sống lập hạnh thiểu dục tri túc (BA Y MỘT BÁT).
16. Phơi quần áo phải kín đáo, gọn gàng (đặt giá phơi sau lưng thất).

=== _[.underline]#II- CÁCH THỨC TU TẬP:#_
Tu viện xin nhắc lại: tu sinh nên chuyên cần tu 2 pháp như sau:

1. _Tu tập Chánh Niệm Tỉnh Giác._
2. _Tu tập Định Vô Lậu._

*A- Tu tập Chánh Niệm Tỉnh Giác.*

1. Đối với tu sinh cấp I, phải rèn luyện tu tập Tỉnh Thức:

a. _Tác Ý khi đi Kinh Hành._
b. _Thân Hành Niệm._
[unstyled]
. Mục đích đạt sức Tỉnh Thức trong 3 oai nghi (đi, đứng và ngồi).
+
2. Đối với tu sinh cấp II, phải rèn luyện sức tỉnh giác:

a. _Hướng Tâm trong Chánh Niệm (luôn sống trong Hiện Tại)._
b. _Khắc phục Hôn Trầm, Vô Ký, và phải siêng năng đi Kinh Hành._
[unstyled]
. Mục đích đạt được sức Định Tỉnh trong 4 oai nghi (đi, đứng, ngồi và nằm).

*B- Tu tập Định Vô Lậu (ngồi tự nhiên).*

1. Đối với tu sinh cấp I, tu tập Chánh Kiến, Chánh Tư Duy:

a. _Quán về Nhân Quả, Vô Thường, Vô Ngã, Duyên Hợp, Duyên Tan, Thân Bất Tịnh và Thực Phẩm Bất Tịnh._
b. _Quán các pháp với từng Tâm Niệm sinh khởi._
[unstyled]
. Mục đích đạt Tri Kiến Giải Thoát, Tâm Vô Lậu, Tâm Bất Động (thấu hiểu như thật nên tâm không còn chướng ngại).
+
2. Đối với tu sinh cấp II, sống với TÂM BẤT ĐỘNG:

a. _Sống với Tâm Giải Thoát, Thanh Thản, An Lạc và Vô Sự._
b. _Đi vào TỨ NIỆM XỨ (Do sống kéo dài với Tâm Bất Động nên Tâm Thanh Tịnh TỰ QUAY VÔ, hoàn toàn không tu tập một pháp môn nào)._
[unstyled]
. Mục đích để VIÊN MÃN TỨ NIỆM XỨ.

Đây là 2 pháp tu căn bản quá rõ ràng rành mạch, để tu sinh tự trắc nghiệm từng giai đoạn đạt hay không đạt, mà tự điều chỉnh lại sự tu tập cho chính mình. Nếu như tu sinh nào ỨC CHẾ hay CĂNG THẲNG rồi sinh bệnh, thì tu sinh ấy đã tu sai pháp của Tu viện, không thực hành đúng theo pháp của Thầy đã dạy. Vì vậy cần nên khắc phục và điều chỉnh cho kịp thời, đúng pháp của Tu viện.


=== XIN LƯU Ý:

Tu sinh cần phải nghe theo người hướng dẫn tu tập và người kiểm tra của từng khu mà Thầy đã giao.

Riêng Khu Chuyên tu bên nam tạm thời chưa có người hướng dẫn, có thể viết thư thưa hỏi Thầy khi gặp trở ngại.

[.text-center]
_Kính ghi_ +
_Tu viện Chơn Như_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== KÍNH GỬI QUÝ TU SINH KHU TIẾP NHẬN!
[discrete]
=== Ngày 07-02-2013

Từ trước đến nay, Tu viện chúng ta lấy Giới luật làm nền tảng tu tập, mà điều cốt lõi chính là *ĂN - NGỦ - ĐỘC CƯ*. Quý vị đến Tu viện tu tập, trước khi vào thất chúng tôi đã có sinh hoạt một số điều nhỏ nằm trong ĂN - NGỦ - ĐỘC CƯ (mà quý vị thường hay mắc phải). Tuy là nhỏ nhưng nó cũng nói lên được cái tâm của mình có tỉnh thức, có xả được hay không. Dù đã có sinh hoạt trước rồi, nhưng khi vào thất tu tập quý vị vẫn vi phạm. Khi được hỏi vì sao thì quý vị trả lời là không biết, bị quên v.v... Vì vậy chúng tôi xin ghi lại những điều nhỏ này để quý vị lưu ý mà tránh được những lỗi nhỏ nhặt:

=== _[.underline]#ĂN:#_

1. Khi đi khất thực, phải ôm bát đi từ từ, nhẹ nhàng, nghiêm trang, không được đội khăn, mũ, nón v.v...
2. Đến kệ cơm, nếu có người đang lấy cơm thì chúng ta đứng ra xa để chờ đợi.
3. Đến kệ cơm, lấy mâm theo thứ tự từ dưới lên trên, từ phải sang trái.
4. Xem mâm thức ăn trước để lấy gia vị và lấy cơm vừa đủ ăn (để tránh trường hợp đi khất thực lần thứ 2).
5. Gia vị trên kệ cơm như tương, chao, muối v.v... quý vị lấy tại chỗ, không được mang nguyên chai, lọ v.v... về thất.
6. Có mì gói, cháo gói thì lấy nước nóng tại chỗ, không được mang phích nước nóng về thất.


=== _[.underline]#NGỦ:#_

1. Luôn giữ gìn giờ giấc nghiêm chỉnh.
2. 2h khuya dậy, phải xếp gọn mùng, mền, chiếu, gối cất vào ngăn tủ.
3. Đến giờ tu không được làm lặt vặt lấn qua 5 - 10 phút (lao tác, tắm giặt, tưới cây, nhổ cỏ v.v... ).
4. Hết giờ tu mới xả nghỉ, không được đi làm sớm 5 - 10 phút (chuẩn bị khất thực, chuẩn bị ngủ v.v...).
5. Trong giờ tu không được phóng dật làm việc lặt vặt.
6. Buổi sáng nằm nghỉ từ 5h đến 6h, không được nghỉ quá giờ.


=== _[.underline]#ĐỘC CƯ:#_

1. Không được nghe băng, đọc sách.
2. Không ra dấu, ra hiệu, viết thư qua lại. 
3. Không cười hay xá chào khi gặp nhau. 
4. Không lao tác chung.
5. Không hỏi chuyện bất kỳ một người nào ngoại trừ người có trách nhiệm trong khu vực của mình tu tập.
6. Không được đi đến thất của người khác.
7. Không được mở cửa thất trống để lấy vật dụng trong thất.
8. Không được lưu ý nhìn ngó ai hoặc công việc của ai.
9. Phải luôn phòng hộ 6 căn để giữ độc cư cho mình, cho người (mọi người phải luôn giữ khoảng cách nhau 3m).
10. Không cất giữ điện thoại.
[unstyled]
. Kính thưa quý tu sinh!

Thầy đã dạy: *“Giữ độc cư thì chúng ta mới ly dục, ly ác pháp được”*. Dù quý vị vào đây tu tập một ngày cũng phải giữ cho được Thánh Hạnh này mới xứng đáng là đệ tử của Phật, của Thầy, mới xứng đáng thọ nhận của đàn na thí chủ và quý vị mới cảm nhận được sự *GIẢI THOÁT*.

Kính mong quý vị hãy cố gắng giữ gìn Giới Luật nghiêm túc để được lợi ích cho mình, cho người, để không phụ công ơn của Thầy.

[cols="^1,^1", frame=none, grid=none]
|===
|Đã duyệt
|_Kính ghi_

|_Thích Mật Hạnh_
|_Ban Quản Lý TVCN_
|===


[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TÂM THƯ CỦA THẦY
Kính gửi quý tu sinh! Trong việc tu tập làm chủ sống chết là một điều lợi ích rất lớn cho con người, vì thế quý tu sinh cần lưu ý như sau:

1. *ĂN:* Ngày một bữa (từ 10h đến 12h trưa).
2. *NGỦ:* Ngày ngủ 5 giờ, cụ thể như sau: trưa từ 12h30 đến 13h30; tối từ 22h đến 2h.
3. *ĐỘC CƯ:* Sống một mình, nếu không hiểu pháp tu hoặc thắc mắc điều gì, xin quý vị viết thư thưa hỏi, hoặc gặp trực tiếp người chịu trách nhiệm quản lý khu vực nơi mình đang tu tập.

Muốn làm chủ Sanh, Già, Bệnh, Chết mà không thực hiện được 3 điều đã nêu trên, thì làm sao làm chủ được. Phải không quý vị?

Cho nên Thầy đề nghị quý tu sinh phải nghiêm chỉnh chấp hành, vì đây là “Khu Chuyên tu”, không cho phép quý vị lơ là thiếu tự giác, không siêng năng đi kinh hành, thân hành niệm, mà chỉ thích ngồi ngủ gà, ngủ gật, mất oai nghi chánh hạnh của người tu sĩ đệ tử Phật.

Vì vậy Ban Kiểm tra sẽ có trách nhiệm gõ cửa hoặc nhắc nhở quý vị. Nếu nhắc nhở quývịtừ2đến3lầnmàquývịkhôngcósựcố gắng khắc phục, thì khi đó Ban Kiểm tra xin mời quý vị ra khu ngoài dành cho người mới tập tu, để tu tập Tỉnh Thức trở lại.

*Ngoài ra, quý vị cần phải lưu ý những điều sau đây:*

- Không được đóng cửa thất, phải mở cửa thường xuyên để kiểm tra.
- Không được phóng dật trong giờ tu tập (đi lao tác, làm cỏ, đốt rác, lá cây...).
- Đặc biệt, không được buộc dây từ cây này sang cây kia để làm nơi phơi quần áo, mùng mền; không nên treo, phơi quần áo nơi cửa sổ, trước cửa thất hoặc trên mái hiên. Nếu tu sĩ Phật giáo mà treo phơi quần áo như vậy thì quý vị nghĩ sao?
- Có văn hóa đạo đức mỹ quan chỗ mình ở không?
- Quý vị là người có đầu óc thẩm mỹ hay vô thẩm mỹ?
- Người có học thức, có đạo đức không bao giờ chấp nhận. Ngược lại, chỉ có những người thiếu hiểu biết nên mới phơi, treo quần áo như vậy. Thật là lối sống bừa bãi đáng chê trách!
- Muốn phơi quần áo thì nên phơi trong phòng tắm, trong thất, không nên đưa ra hành lang hoặc ngoài sân xung quanh thất.
- Sau khi dứt lời, Thầy rất mong các con là đệ tử của Thầy thì phải sống như thế nào mới xứng đáng là đệ tử của Thầy, còn nếu thấy Thầy khó quá, thì nên trở về trụ xứ của mình.

[.text-center]
_Kính thư_ +
_Thầy của các con_ +
 + 
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TIẾP NHẬN NGƯỜI VÀO TU HỌC
[discrete]
=== Tâm Thư Trưởng Lão Gửi Ngày 17-11-2010

Kính gửi các con! Có những điều quan trọng trong sự tiếp nhận người vào Tu viện tu tập:

1. Người phá hạnh độc cư dù chỉ một lần cũng nên mời họ ra khỏi Tu viện.
2. Từ những cư sĩ đến những tu sĩ dù là Hòa Thượng, khi đến Tu viện đều phải trình pháp môn tu tập của mình, nếu không mà tự tu thì cũng nên mời họ ra khỏi Tu viện.
3. Tu viện là nơi tu hành chánh pháp của Phật, nếu ai đến đây mượn chỗ tu hành thì mời ra khỏi Tu viện.
4. Nếu những cư sĩ hay những tu sĩ được chấp nhận cho ở trong Tu viện tu tập thì phải ăn mặc đồng phục như nhau, không nên viện cớ vì hệ phái này hệ phái khác, mà phải hiểu đây chỉ có những tu sĩ Phật giáo Việt Nam mà thôi.
5. Tu viện chấp nhận những người quyết tâm tu giải thoát, còn những người đến đây xin tu một ngày, hoặc hai, ba ngày, hoặc một tháng, hai, ba tháng rồi về, thì không nên nhận, hãy cho họ về ngay. Vì để những người này sẽ làm bận rộn Tu viện phải lo chỗ ăn, chỗ nghỉ, giấy tờ tạm vắng, tạm trú và những lý lịch rất là phiền phức.
6. Khi những cư sĩ hay tu sĩ mới đến tu tập, thì con nên đọc cho họ nghe những điều trong bức thư này, để ngay đó họ rời khỏi Tu viện mà các con khỏi phải khai báo giấy tờ.
7. Tu viện cần có những người có chí tu tập làm chủ sinh, già, bệnh, chết, chớ không chấp nhận những cư sĩ hay tu sĩ đi lang thang.
8. “Pháp bất vị thân”; ở Khu Tiếp nhận, con phải cứng rắn nói thẳng, nói thật và mời những người tu thử, tu chơi ra về, để các con được an ổn tu hành.
9. Những cư sĩ hay tu sĩ đến đây đảnh lễ, thật tâm cầu pháp tu hành thì chấp nhận, còn những cư sĩ hay tu sĩ tính tình ngang bướng, thường đem những kiến giải bã mía ra tranh luận hơn thua thì mời ra khỏi Tu viện.
10. Giờ giấc ở đây đã qui định, người nào tu sai giờ giấc thì mời ra khỏi Tu viện.
11. Ăn uống phi thời thì nên mời ra khỏi Tu viện.
12. Ngủ phi thời thì nên mời ra khỏi Tu viện.
13. Thất phải mở cửa trong giờ tu tập, không được treo chăn màn hay đóng đinh treo y, áo, nếu làm sai, xin mời ra khỏi Tu viện.
14. Giường nằm trong thất không được di dời, nếu di dời sẽ mời ra khỏi Tu viện.
15. Thất phải giữ gìn vệ sinh từ nơi ngủ nghỉ, và phòng vệ sinh phải sạch sẽ.
16. Trên tường không được dán giấy, viết chữ, không được đóng đinh treo hình ảnh, dù là hình ảnh của Phật.
17. Xung quanh thất phải dọn dẹp sạch sẽ, không trồng hoa kiểng; người nào làm sai thì sẽ mời ra khỏi Tu viện.
18. Người mới đến đây chưa hiểu pháp tu hành thì nên hỏi người hướng dẫn.
19. Pháp tu hành ở đây là pháp tu hành thực tế, nếu tu hành thì sẽ có giải thoát ngay liền. Những người tu thử, tu chơi thì nên rời khỏi Tu viện.
20. Tu viện chỉ mong những người có chí lớn, có quyết tâm tu chứng đạo để làm sáng tỏ Phật giáo.

Hai mươi điều trên đây con nên đọc cho những người mới đến, để họ lượng sức mình có tu tập được thì quyết tâm bền chí ở lại tu hành, còn không thì hãy ra về.

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== BỨC TÂM THƯ GỬI QUÝ TU SINH
[discrete]
=== Ngày 31-05-2011

Kính gửi các con! Người tu sĩ bị hôn trầm nhiều là người tu sĩ lười biếng, bởi Phật có dạy pháp đối trị tâm lười biếng đó, nhưng những người tu sĩ ngồi thiền gục tới gục lui, là do đã tập thành thói quen theo sự nhịp nhàng, an lạc của THÂN, TÂM, nên ý thức không biết thân đang gục. Vì thế, người gác thiền báo cho biết sự tu sai đó, thay vì hành giả nghe nói mình tu sai thì cố gắng sửa sai.

Người tu tập lâu năm vẫn tu sai pháp, gục là do tướng hôn trầm, thùy miên, vô ký cản lối. Khi tướng này hiện ra, nếu người tu sĩ không siêng năng phá nó bằng pháp môn THÂN HÀNH NIỆM, thì sự tu hành của họ sẽ hoài công, vô ích, và khi ngồi thiền có cảm nhận an lạc, là rơi vào trạng thái tưởng rồi cứ gục tới, gục lui.

Bất cứ người nào, từ cư sĩ đến tu sĩ, dù là chức vụ Thượng Tọa hay Hòa Thượng trong Giáo hội, về Tu viện tu tập đều phải nghe lời người hướng dẫn chỉ dạy trong từng khu, để được kiểm nghiệm sự tu tập của quý vị. Trong Phật giáo có 3 pháp môn cơ bản cho người mới vào tu tập:

1. Sống HẠNH ĐỘC CƯ là phương pháp sống một mình. Khi vào Tu viện xin tu tập, trong Tu viện cấp cho một cái thất; khi nhận thất tu tập thì không đi sang thất khác nói chuyện, chỉ sống một mình trong thất, dù cha mẹ, anh chị em, bạn bè thân hữu tới thăm cũng không giao tiếp.
2. Pháp môn NHƯ LÝ TÁC Ý là một pháp môn ngồi chơi, khi tâm có niệm khởi thì liền tác ý... theo sự hướng dẫn. Ví dụ: _“Tâm như cục đất, ly dục ly ác pháp đi”_.
3. Pháp môn THÂN HÀNH NIỆM là pháp môn phá hôn trầm, thùy miên, vô ký. Người muốn tu tập phá hôn trầm, thùy miên, vô ký thì hãy siêng năng tu tập pháp môn này để phá sạch tâm si mê, và nên nhớ:
[unstyled]
. Không phải lúc nào cũng đi kinh hành, mà còn phải đi THÂN HÀNH NIỆM khi bị hôn trầm, thùy miên, vô ký; còn bao nhiêu giờ khác thì ngồi chơi như người vô sự, đừng tu tập pháp môn nào khác nữa.

Người siêng năng tu tập chuyên cần, không bao lâu sẽ đạt được kết quả giải thoát, vì pháp này là con đường tắt của Phật giáo do kinh nghiệm tu hành mà thầy truyền lại cho các con, vì biết mình trụ thế không còn bao lâu nữa. Vậy các con phải tinh cần, đừng bỏ phí thời gian.
[.text-center]
[verse]
_“Tấc bóng thời gian, một tấc vàng 
Tấc vàng tìm được không gì khó
Tấc bóng thời gian khó hỏi han”_

Trong các con, người nào SỐNG MỘT MÌNH trọn vẹn THÂN, KHẨU, Ý từ 3 tháng đến 6 tháng, sẽ được Thầy trực tiếp hướng dẫn tu tập; còn sống chưa được thì được quý thầy cô hướng dẫn tu học từ cấp 1 đến cấp 8, theo đúng chương trình BÁT CHÁNH ĐẠO.

Sau cùng, Thầy có lời thăm và chúc các con có đầy đủ ý chí, nghị lực, quyết tâm tu hành tìm cầu sự giải thoát nơi chính mình, để trở thành những đệ tử ưu tú của Thầy.

[.text-center]
_Kính thư_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== HIỂU ĐÚNG PHẬT PHÁP
[discrete]
=== Tâm Thư Thầy Gửi Quý Tu Sinh

Kính gửi các con! Tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ là các con đã biết đúng pháp; nhưng tâm
còn lơ mơ, thiếu ý chí và không quyết tâm, nên con đường tu còn xa lắm, biệt mù; có thể suốt đời không chứng đạo.

- Đạo Phật là đạo của con người, nên sáng hiểu đạo chiều chứng đạo.
- Đạo Phật là đạo trí tuệ, chứ không phải là đạo con cóc, thế mà các con cứ ngồi như cóc có ích gì?
- Đạo Phật là đạo trí tuệ, vì ai biết dùng Tri Kiến là giải thoát ngay, khỏi cần tu.
- Đạo Phật là đạo như thật, ai hiểu đạo là chứng đạo.
- Đạo Phật là đạo sống một mình, không chơi với ai cả.
- Đạo Phật là đạo vô sự, có đâu đi trồng cây trái, đào mương đào rãnh, làm rào làm giậu!

[.text-center]
_Kính thư_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TÂM THƯ GỬI QUÝ PHẬT TỬ ĐẾN TU VIỆN TU HỌC
[discrete]
=== Ngày 01-10-2009

Kính gửi quý Phật tử! +
Kính thưa quý vị!

Những người Phật tử vào Tu viện với mục đích là tu tập để làm chủ SINH, GIÀ, BỆNH, CHẾT, cho nên phải sống đúng giới hạnh: ĂN, NGỦ và ĐỘC CƯ cho trọn vẹn; còn chưa sống được như vậy thì nên trở về trụ xứ của mình mà luyện tập sống cho đúng giới hạnh; chừng nào sống được như vậy mới vào Tu viện tu học tiếp TÂM LY DỤC, LY BẤT THIỆN PHÁP. Người nào không sống đúng giới hạnh, thường vi phạm một trong ba giới hạnh trên đây thì xin vui lòng rời khỏi Tu viện.

Tu viện là nơi để cho những người quyết tâm về tu hành cầu giải thoát, chớ không phải là nơi để cho những người về an dưỡng, đi tới, đi lui như đi chợ. Đừng mượn nhà của Tu viện để ở, mượn cơm của Tu viện để ăn, ăn rồi lại tập trung đi nói chuyện tào lao, lại còn đi dạo làng trên xóm dưới vào quán mua bánh trái, đường sữa về ăn thêm. Trong khi mọi người ăn chỉ một ngày một bữa, còn mình thì ăn thêm lặt vặt thật là xấu hổ! Những người ăn uống phi thời như vậy là phá hoại Tu viện.

Để đảm bảo sự an ninh yên ổn cho Tu viện, khi mọi người đến đều phải đăng ký lý lịch, hộ khẩu tạm trú, tạm vắng. Đó là để bảo vệ tự do tín ngưỡng tu hành của mọi người trong Tu viện.

Bổn phận của người công dân là phải tuân hành luật pháp của Nhà nước. Còn riêng những người nào tránh né không đăng ký hộ khẩu tạm trú, tạm vắng, thì Tu viện cần phải mời những người này ra khỏi. Đó là để bảo vệ cho những người khác tu hành. Nếu những người này không chấp nhận rời khỏi Tu viện, thì những người có trách nhiệm đăng ký hộ khẩu tạm trú, tạm vắng nên báo cáo cho ngành An ninh Nhà nước biết, để kịp thời ngăn chặn những người phá hoại Tu viện.

Vì bảo vệ Tu viện để mọi người được yên ổn tu hành, nên Thầy cho phép các con phải làm việc kiểm tra chặt chẽ đối với những người đến, đi, ở trong Tu viện mà không khai báo, hoặc đến ở năm, mười ngày rồi lại đi về; về trong năm, mười ngày rồi lại đến; cứ đến, đi như vậy làm cho người đăng ký rất khó làm việc. Những người này không chấp nhận cho họ ở trong Tu viện. Nhất là những người đến ở đăng ký một tháng hoặc hai tháng, nhưng chỉ ở có năm, mười ngày rồi lại bỏ ra về. Đi và về như vậy chứng tỏ những người này không có thiện chí tu hành. Họ không phải là những người tu hành thật sự; cần phải mời họ ra khỏi Tu viện, vì họ là những người phá hoại Tu viện, đến làm động những người khác tu hành. Họ xem Tu viện là nơi du lịch nên muốn đến, muốn đi lúc nào cũng được. Những hạng người này cần phải cảnh giác, nhất là những người quen mặt rồi sinh ra lờn mặt. Tu viện hiện nay không chấp nhận những hạng người này ở trong Tu viện. Nhân tiện đây, Thầy xin mời một số người không giữ hạnh độc cư, thường lén lút nói chuyện, lấy cớ bệnh đau để đi ra, đi vào trị bệnh. Đó là những hành động phá độc cư của Tu viện.

Nếu vào Tu viện thì phải bền chí tu tập ngày đêm để làm chủ bệnh, thì còn có thì giờ đâu rảnh rang mà đi nói chuyện. Bởi vậy, chỉ có những người vào Tu viện nhưng không quyết tâm tu tập nên ăn không ngồi rồi, vô công rỗi việc, mới đi từ thất này tới thất khác kiếm người đồng bệnh nhiều chuyện. Đó là những hành động phá hoại Tu viện. Những người này nên rời khỏi Tu viện; đừng để Thầy nêu tên tuổi, đuổi ra khỏi Tu viện thì xấu hổ lắm; rồi đây không còn nhìn mặt người khác được.

Người tu hành thì phải giữ gìn đức hạnh và siêng năng tu tập cho ra người tu hành, thì mới được xem là đệ tử của Tu viện CHƠN NHƯ. Khi thấy mình chấp hành nội quy không nghiêm chỉnh thì nên rời khỏi Tu viện, đừng để bị đuổi mà mang tiếng muôn đời. Một em bé học sinh bị đuổi học, nhưng vì em còn bé thơ nên mọi người tha thứ và xem đó là một em bé “ăn chưa no, lo chưa tới”; còn các Phật tử không còn là em bé, mà là người lớn, có đủ trí tuệ hiểu biết, đến Tu viện tu tập làm chủ sự sống chết, nhưng cớ sao lại đi nói chuyện phá hạnh độc cư, phá nội quy Tu viện? Một em bé làm sai, cô giáo hay cha mẹ bắt phạt, đôi khi bị cô giáo đuổi. Còn Phật tử phạm vào nội quy, phá hạnh độc cư của Tu viện, đi nói chuyện thì phạt thế nào?

Một người lớn như các Phật tử không lẽ phạt quỳ hương, hay đánh năm, mười roi, mà chỉ có bị phạt là đuổi ra khỏi Tu viện. Quý Phật tử có biết không?

Một người công dân tốt trong một đất nước thì phải chấp hành luật pháp nghiêm chỉnh, không hề vi phạm pháp luật của Nhà nước. Còn người công dân thường vi phạm pháp luật của Nhà nước, người công dân như vậy là người công dân có tiền án, tiền sự; không xứng đáng là người công dân trong nước độc lập.

Ở trong Tu viện cũng vậy, tất cả Phật tử phải thi hành nội quy Tu viện nghiêm chỉnh. Ai vi phạm nội quy Tu viện, thường đi tới, đi lui nói chuyện lén lút là những người phá hoại Tu viện, cần phải mời ra khỏi Tu viện. Nhất là những người nào ở trong Tu viện hai, ba tháng rồi không đăng ký tạm trú; nếu không đăng ký thì mời ra khỏi Tu viện.

Tu viện là nơi để cho mọi người về đây học tập đạo đức nhân bản - nhân quả, và nhất là tu tập để làm chủ sự sống chết, vì thế nếu ai vi phạm nội quy, phá hạnh độc cư thì Tu viện không chấp nhận. Đây là một bức thư cảnh báo cho quý Phật tử biết, để tránh những điều vi phạm nội quy Tu viện.

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TIÊU CHUẨN CHỌN LỰA NGƯỜI VÀO CHUYÊN TU
[discrete]
=== Tâm Thư Thầy Gửi Quý Tu Sinh

Nếu là trường học thì phải có kỷ luật rõ ràng, nghiêm túc.

Nếu về Tu viện chỉ để hỏi pháp hoặc thọ Bát Quan Trai thì phải có thời gian nhất định, cụ thể rõ ràng.

Còn về tu học thì phải chấp hành đúng Thanh Quy; có như vậy thì kết quả tu học mới có chất lượng, không uổng công người chỉ dạy để cho mọi việc được tốt đẹp.

Nếu Thầy không chấn chỉnh Tăng đoàn và Cư sĩ đoàn, thì không biết chừng nào có người chứng đạo. Tu sĩ mà sống thiếu giới luật đức hạnh, oai nghi chánh hạnh không có thì tu tập được cái gì?

Cho nên, THỜI KHÓA TU TẬP TRONG THỜI ĐỨC PHẬT và tập THANH QUY Tu viện CHƠN NHƯ được nhuận lại trong lúc này, là để đưa ra kịp thời và gạt bỏ những người không có ý chí quyết tâm tu tập giải thoát, thường phá hạnh độc cư. Mình đã tu tập không được, lại còn lôi thêm một số người khác cũng tu tập không được; thật là xót xa!

Từ lâu, Thầy cứ nghĩ rằng mọi người khi vào Tu viện là quyết chí tu tập cho đến khi giải thoát, nhưng nào ngờ, nghiệp lực thói quen lâu đời, nên quá khó khăn buông bỏ cái ăn, cái ngủ, cái nói chuyện, v.v... nên sống độc cư chịu không nổi.

Nhập thất mà ra, vào như vậy là nhập thất để có tiếng là nhập thất tu hành, chớ có tu hành được những gì đâu. *Tâm chưa xả sạch chướng ngại pháp mà vào thất là chưa thông hiểu phương pháp tu hành.*

Muốn nhập thất tu hành là để đi đến làm chủ SANH, GIÀ, BỆNH và CHẾT, thì phải có người trắc nghiệm xem mình tu tập tâm Tỉnh Thức đến mức độ nào thì mới được vào thất tu tập, chớ không phải muốn vào thất thì vào.

Khi nhập thất tu tập thì người tu sĩ giới luật không còn vi phạm những lỗi nhỏ nhặt nào, những oai nghi chánh hạnh phải được tròn đủ, hạnh độc cư phải nghiêm chỉnh không đi nói chuyện bất cứ một ai cả. Nếu tu tập giữ gìn giới luật nghiêm chỉnh, sợ hãi trong những lỗi nhỏ nhặt, hằng ngày sống đúng những oai nghi chánh hạnh, ăn uống tiết độ không phi thời, thường đi kinh hành nhưng lại xả tâm theo pháp TỨ CHÁNH CẦN thường ngăn ác diệt ác pháp, sanh thiện tăng trưởng thiện pháp, luôn luôn giữ gìn tâm thanh thản, an lạc và vô sự; những người tu tập đúng như vậy thì không bao giờ nhập các định tưởng và bị các pháp tưởng. Họ sẽ thực hiện đúng tâm vô lậu và đầy đủ Tam Minh.

Còn nếu họ không giữ gìn giới luật đức hạnh nghiêm chỉnh, không phòng hộ 6 căn, thì dù có tu tập pháp nào đi nữa họ cũng sẽ rơi vào các pháp tưởng. *Nhất là cũng dễ nhận ra người bị nhập vào tưởng pháp, vì họ nói nhiều.*

Sau cùng, thầy có lời thăm và chúc các con có đầy đủ ý chí, nghị lực, quyết tâm tu hành tìm cầu sự giải thoát nơi chính mình, để trở thành những đệ tử ưu tú của Thầy.

[.text-center]
_Kính thư_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== NGĂN NẮP VỆ SINH
[discrete]
=== Thông Báo Của Tu viện

Kính gửi quý tu sinh! Xin quý tu sinh lưu ý! Trong sinh hoạt hằng ngày, chúng ta cần phải có sự ngăn nắp, gọn gàng,
sạch sẽ, lịch sự...

Trong mỗi thất có một cái thau (chậu) và một cái xô (thùng). Cái thau dùng để giặt quần áo, cái xô dùng chứa nước sạch, để chúng ta lấy nước từ đó mà tắm, giặt, rửa mâm bát.

Nay Ban Quản lý xin nhắc nhở vài điều sau đây:

1. Không được ngâm giặt quần áo trong thùng;
2. Không rửa mâm bát trong thau ngâm giặt quần áo;
3. Hãy treo móc quần áo trong buồng tắm, rồi đem ra ngoài phơi.

Chúng ta đang sống trong một tập thể, nên cần giữ vệ sinh chung. Nhưng dù là sống một mình, chúng ta cũng phải ăn ở vệ sinh sạch sẽ, như vậy mới đúng là người sống đạo đức không làm khổ mình, khổ người.

Kính xin quý tu sinh hãy vui lòng thực hiện tốt.

[.text-center]
_Kính ghi_ +
_Ban Quản lý Tu viện Chơn Như_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== VỆ SINH TÂM
[discrete]
=== Tâm Thư Thầy Gửi Quý Tu Sinh

Kính gửi tu sĩ và cư sĩ! Kính thưa quý
vị! Có hai điều Thầy xin nhắc nhở quý vị

*icon:asterisk[] Điều thứ nhất:*
[none]
. Tu tập theo Phật giáo vốn là làm vệ sinh tâm mình, cho nên Phật dạy là LY DỤC, LY ÁC PHÁP, chớ không phải ức chế ý thức, làm cho nó tê liệt không khởi niệm như các nhà sư Đại thừa và các nhà sư Đông Độ Trung Quốc.

. Vệ sinh tâm mình mà đời sống của quý vị không vệ sinh, xung quanh chỗ quý vị cư ngụ như đống rác không hề quét dọn một chổi; bên ngoài chỗ ở không làm vệ sinh thì bên trong tâm của quý vị làm vệ sinh cái gì?

. Nhìn bên ngoài đời sống mà biết được sự tu tập sai đúng của quý vị; tu làm Phật, không lẽ Phật ở bẩn thỉu vậy sao? Nhìn chỗ quý vị ở tu là biết ngay quý vị có tu được không.

. Xin quý vị cần lưu ý: đây là điều thứ nhất.

*icon:asterisk[] Điều thứ hai:*
[none]
. Tu hành có phải là làm một việc gì lén
lút mà phải đóng cửa kín mít? Tu hành là một việc làm quang minh chánh đại, chớ đâu phải phòng the của đôi tân hôn mà che màn giăng lưới.

. Tu như vậy có ích lợi gì? Quý vị hãy bỏ dẹp đi, còn nếu không bỏ dẹp được thì nên về giúp cha mẹ, quét nhà, nấu cơm cho con, cho cháu còn có ích lợi cho đời; chớ tu như vậy chẳng đi đến đâu cả, mà còn mang nợ đàn na thí chủ; mà còn mang tiếng trốn tránh lao động, làm ký sinh trùng ăn bám xã hội.

*Tu là làm vệ sinh tâm như trên đã nói, vậy làm vệ sinh tâm như thế nào?*

Khi trong tâm quý vị có cọng rác bẩn nào thì quét nó đi, quét đi thì tâm quý vị sẽ không còn rác bẩn nữa, và như vậy gọi là làm vệ sinh; còn không có rác bẩn thì thôi, cớ sao lại cứ quét mãi, như vậy quý vị có phải là người khùng không?

Tu là làm cho thân tâm mình không bị ô nhiễm thêm vật chất cuộc đời, cớ sao quý vị để thân tâm mình ô nhiễm gạo lức muối mè, hay bất cứ điều gì khác? Có gạo lức muối mè thì không đau nhức, không gạo lức muối mè thì thân đau nhức, như vậy đau nhức là vì gạo lức muối mè, chớ đâu phải thân quý vị đau nhức; quý vị đã bị nhiễm gạo lức muối mè. Muối mè đâu phải chỉ là vật duy nhất bổ dưỡng; người ta khéo đặt ra làm cho tư tưởng quý vị bị ảnh hưởng gạo lức muối mè. Những kiến thức gạo lức muối mè như vậy là những kiến thức làm mê hoặc lòng người. Giải thoát của đạo Phật là buông xuống hết, cớ sao lại thêm vào gạo lức muối mè?

Giải thoát của Phật giáo rất là đơn giản, đâu có gì cầu kỳ khó khăn, đâu có gì ngoài cuộc sống của con người? Họ cũng ăn, cũng làm việc bình thường. Nhưng họ khác hơn người thường là luôn luôn lúc nào cũng làm chủ tâm mình; vì thế đời sống của họ vui vẻ, an lạc; không có một việc gì làm cho họ buồn phiền, giận hờn hay cay cú.

Người nào có duyên, sáng nghe Phật thuyết thì chiều đã hoàn toàn giải thoát, chớ có tu tập cái gì nhiều đâu; chỉ cần buông xuống, không hơn thua ai cả là giải thoát. Cho nên đạo Phật duy nhất chỉ biết LY DỤC, LY ÁC PHÁP là giải thoát ngay liền.

Xin quý vị cần lưu ý: đây là điều thứ hai.

[.text-center]
_Kính thư_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== BA Y MỘT BÁT - GIỮ GÌN VỆ SINH
[discrete]
=== Tâm Thư Thầy Gửi Ngày 03-06-2010

Kính gửi quý thầy, cô cùng nam, nữ cư sĩ! Đối với đạo Phật, đời sống nam nữ tu sĩ chỉ có ba y một bát. Vì vậy mà nam, nữ cư sĩ muốn sống tu tập ở Tu viện thì phải sống như tu sĩ, chỉ ba y một bát mà thôi. Người nào sống không đúng hạnh này, Thầy xin quý vị vui lòng rời khỏi Tu viện, vì mục đích Tu viện là dựng lại đời sống của người tu sĩ và cư sĩ Phật giáo thời đức Phật. Vậy quý sư thầy, cô và các nam nữ cư sĩ phải nêu cao gương hạnh buông xả; nếu vì một lý do gì không sống được ở đây, thì Thầy chấp nhận cho quý vị rời khỏi Tu viện.

Sau khi quý vị được cấp cho mỗi người một chiếc thất sạch sẽ vệ sinh, đầy đủ ngăn nắp, mà quý vị sống không ngăn nắp, không vệ sinh, bừa bãi, dơ bẩn, trên vách đóng đinh treo hình ảnh Thầy và hình ảnh Phật, đó là một việc làm thiếu sự cung kính và tôn trọng. Vì nơi đây là chỗ ở, chớ không phải chỗ thờ phụng.

Cấm không được đóng đinh trên vách, không được giăng màn, che kín. Cửa cái và cửa sổ phải mở rộng, không được đóng kín.

Xung quanh thất và trong khung viên thất của quý vị phải dọn dẹp, giữ gìn vệ sinh sạch đẹp, không được để dơ bẩn. Nhất là khi ăn uống xong, những bao bì sữa bằng nhựa, giấy và những bọc ni lông phải được tự quý vị thiêu đốt làm vệ sinh, không được đem ném bỏ một nơi nào trong khuôn viên Tu viện hoặc nhờ một người khác giúp giùm.

Ban Kiểm tra vệ sinh phòng ốc hằng nửa tháng sẽ đến khám xét. Nếu quý vị sống không vệ sinh, sống bừa bãi, thì Ban Kiểm tra sẽ mời quý vị ra khỏi thất và khoá cửa lại.

Tất cả tài sản này là của quý Phật tử khắp nơi, vì thế Ban Bảo trợ và Giữ gìn tài sản chung này phải có bổn phận giữ gìn và bảo quản. Nếu người tu sĩ và cư sĩ nào ở trong Tu viện mà không giữ gìn vệ sinh thì được mời ra khỏi.

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== PHẬT PHÁP TU HÀNH KHÔNG KHÓ
[discrete]
=== Tâm Thư Thầy Gửi Quý Tu Sinh

Đúng như tựa đề của bài pháp này, nên đức Phật dạy: _“Pháp Ta không có thời gian, đến để mà thấy!”_. Có nghĩa là Phật pháp không có dụng công tu tập như các pháp môn ngoại đạo, chỉ cần hiểu biết tính chất của các pháp thế gian là VÔ THƯỜNG, VÔ NGÃ, thì người có trí liền BUÔNG XẢ sạch các pháp. Nhờ BUÔNG XẢ sạch các pháp thế gian, nên không có pháp nào làm ĐỘNG TÂM họ được.

Khi tâm BUÔNG XẢ sạch các pháp thế gian, thì tâm luôn luôn ở trong trạng thái BẤT ĐỘNG, THANH THẢN, AN LẠC, VÔ SỰ, một trạng thái giải thoát mà người tu sĩ Phật giáo nào cũng đều tha thiết muốn sống được với nó. Nhưng muốn sống với nó phải bằng cách nào đây?

Để trả lời câu hỏi này, thì chúng tôi xin quý vị hãy lắng nghe và suy tư cho chín chắn thì mới biết rõ: từ lâu mọi người đều hiểu không đúng chánh pháp của Phật, nên dụng công tu tập từ ngày này qua ngày khác mà kết quả chẳng có gì. Chính sự hiểu sai Phật pháp, mà quý vị tốn rất nhiều công sức tu tập, nhưng xét lại chẳng có lợi ích gì cho bản thân, mà còn xa lìa Phật pháp, vì thế tu mãi mà không tìm thấy GIẢI THOÁT.

Có những người tu tập nhiều năm gần như suốt cả cuộc đời, thế mà vừa nghe bạn đồng tu gõ cửa và nói rằng: _“Con khuyên thầy đứng dậy đi đi!”_; vừa nghe lời khuyên nhủ của bạn đồng tu, thay vì nói lời cảm ơn, nhưng ngược lại, thầy này nói: _“Ngồi không được à!?”_. Nghe nói vậy, vị thầy đi kiểm tra liền bỏ đi.

Sau khi vị thầy đi kiểm tra quay lại, thì vị thầy kia ra giữa đường chặn lại và nói: _“Thầy có nhìn thấy tôi ngủ gật bao giờ chưa? Nếu tôi ngủ gật, tôi sẽ rời khỏi Tu viện ngay lập tức. Người ta đang ở trong định, mà thầy làm vậy là phá người ta, là xâm phạm nhân quyền. Tôi có thể ngồi 5 - 6 tiếng đồng hồ; Trưởng Lão cho phép tu trong bốn oai nghi. Thầy đi kiểm tra theo dõi tôi thế nào tôi biết hết”_. Lúc bấy giờ, thầy đi kiểm tra nói: _“Con thấy thầy mắt nhắm và gật”_. Khi nói xong lời này, thấy mình không thể khuyên được vị thầy đó, nên thầy đi kiểm tra xá và nói: _“Con xin sám hối thầy!”_. Khi đó, vị thầy kia mới đi vô thất.

Qua những sự đối đáp này, đã làm cho mọi người biết vị thầy đó tu hành không xả được tâm, mà ức chế tâm nên mới bộc phát cơn sân dữ dội như vậy. Thật đáng thương thay, bỏ hết cuộc đời để tu tập, mà giờ đây tâm tánh vẫn còn như người thế gian! Do thấy sự tu tập này mà Thầy viết bức tâm thư gửi các con, để các con xét lại sự tu tập của mình, ngõ hầu sự tu tập của các con không còn sai lạc nữa.

Sự GIẢI THOÁT của Phật pháp rất đơn giản, chỉ cần sống TỰ NHIÊN với tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ; sống mà không có sự tu tập gò bó thân tâm thì mới thấy sự GIẢI THOÁT chân thật của đạo Phật. Còn ngược lại, dụng công tu tập làm gò bó thân tâm để tâm BẤT ĐỘNG, thì làm sao thấy sự GIẢI THOÁT. Phải không thưa quý vị?

Từ lâu mọi người hiểu sai Phật pháp, nên cố gắng tu tập, vì thế mà không có một vị sư, thầy nào làm chủ SINH, GIÀ, BỆNH, CHẾT như Phật.

Dù sử dụng trong bốn oai nghi: đi, đứng, nằm, ngồi, mà tâm vẫn tự nhiên như người NHÀN DU, VÔ SỰ; đó là người đã BUÔNG XẢ sạch. Vì thế, họ không còn tu tập một pháp môn nào nữa cả...

Bởi vậy, người nào hiểu đúng Phật pháp là phải cảm nhận được tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ. Nhờ có cảm nhận được tâm như vậy, nên họ đã trở thành CON TÊ NGƯU MỘT SỪNG luôn luôn sống MỘT MÌNH.

Ngược lại, người nào không cảm nhận được tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ, thì nên theo pháp NHƯ LÝ TÁC Ý để hằng ngày ngăn và diệt tất cả ác pháp, thì mới mong BUÔNG XẢ tất cả các pháp thế gian; nhưng phải bền chí trong một thời gian dài.

Khi sống được với tâm BẤT ĐỘNG, thì ngũ triền cái và thất kiết sử không làm sao tác động được, vì thế, không cần phải tu tập pháp môn ly dục, ly ác pháp mà tâm vẫn tự ly dục, ly ác pháp. Như vậy, chỉ cần sống với tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ là tâm đã xả sạch. Hiểu như vậy mới thấy Phật pháp rất nhiệm mầu.

Đối với BỆNH TẬT và tất cả các ÁC PHÁP, khi gặp tâm BẤT ĐỘNG, THANH THẢN, AN LẠC và VÔ SỰ nó đều lìa xa khỏi thân tâm ngay tức khắc. Như vậy, BỆNH TẬT và tất cả các ÁC PHÁP không còn tác dụng vào thân tâm được nữa; đó là trạng thái NIẾT BÀN trong cuộc sống, chớ không phải đợi chết mới vào NIẾT BÀN. Vì thế, đức Phật dạy: _“Pháp Ta không có thời gian, đến để mà thấy!”_

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== CHẤP HÀNH NỘI QUY
[discrete]
=== Thông Báo Của Thầy

Kính gửi các con!

1. Bất cứ một người tu sĩ hay cư sĩ tu tập ở đâu, khi đến đây đều được kiểm tra, nếu tu sai pháp đều được mời ra khỏi Tu viện, còn đúng pháp ở cấp độ nào được xếp lớp ở cấp độ đó.
2. Người nào giữ gìn đúng ĂN, NGỦ thì được xếp vào cấp 2.
3. Cấm ngồi thiền nhiều, ai không nghe thì mời ra khỏi Tu viện.
4. Ai đến đây tu thử xin mời họ về.
5. Chỉ chấp nhận những người cần tu giải thoát.
6. Những người ở xa đến thăm Tu viện, chỉ chấp nhận cho ở lại một tuần lễ.
7. Vào Tu viện ăn mặc đơn giản, không nên trang điểm.
8. Muốn thăm quan phải có người trong Tu viện đưa đi.
9. Không đến thất người tu nói chuyện.
61
HƯỚNG DẪN NHẮC NHỞ TU SINH
 10. Không tập trung đông người, làm mất sự thanh tịnh, trang nghiêm của Tu viện.
11. Không tự lén lút đi tham quan Tu viện một mình.
12. Đến Khu Tiếp nhận, không nên đi từ thất này đến thất khác.
13. Không nên tự xuống Nhà bếp.
14. Không nên đem kinh sách ngoại đạo vào Tu viện.

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== LÀM CHỦ THỜI GIAN
[discrete]
=== Thông Báo Của Tu viện

Kính thưa quý tu sinh! Thầy luôn nhắc nhở: _“Tấc bóng thời gian, một tấc vàng...”_, cho nên chúng ta cần phải giữ
gìn nội quy, giờ giấc ngủ nghỉ, lao tác cho thật nghiêm chỉnh.

Mỗi ngày có bốn thời tu, mỗi thời có ba giờ đồng hồ. Vậy mong quý tu sinh hãy giữ gìn cho trọn vẹn ba giờ tu tập trong bốn thời, đừng làm việc lặt vặt, nhỏ nhặt lấn vào đầu giờ tu hoặc cuối giờ tu như lau quét, nhổ cỏ, tưới cây, tắm giặt, lấy nước, v.v... *Thầy dạy chúng ta trước tiên phải làm chủ giờ giấc, kế đến là làm chủ thân tâm.*

Kính xin quý tu sinh hãy cố gắng khắc phục, để làm đúng theo lời Thầy đã dạy.

[.text-center]
_Kính ghi_ +
_Ban Quản lý Tu viện Chơn Như_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== BẢY ĐỨC HẠNH CỦA NGƯỜI TU THEO PHẬT GIÁO

Đức Phật dạy bảy đức hạnh rất tuyệt vời, nếu một người thực hiện bảy đức hạnh này thì ngay trong đời này đã tìm
thấy sự giải thoát ngay liền, không cần phải tu tập pháp nào khác nữa.

- Nếu sống với đức hạnh thứ nhất: *_“Thích giản dị, không thích sống rờm rà, cầu kỳ”_*, đó là một lối sống đơn giản, không hao tốn tiền bạc, không rờm rà, ít muốn biết đủ; đức hạnh rất phù hợp với người tu sĩ Phật giáo.
- Nếu sống với đức hạnh thứ hai: *_“Ưa thích yên lặng, không thích nói nhiều”_*, đó là một lối sống trầm lặng, sống độc cư, sống một mình; đức hạnh này rất phù hợp với con đường tu tập giải thoát của Phật giáo.
- Nếu sống với đức hạnh thứ ba: *_“Ít ngủ nghỉ, không ham ngủ”_*, đó là lối sống của người thông minh, sáng suốt, minh mẫn, tỉnh giác. Những người có lối sống như vậy là lối sống của người tu sĩ Phật giáo.
- Nếu sống với đức hạnh thứ tư: *_“Không kết bè, kết bạn, không nói những điều vô ích”_*, đó là lối sống độc cư phòng hộ sáu căn, lối sống của những bậc chân tu; của những người thoát tục; của những người xuất thế gian.
- Nếu sống với đức hạnh thứ năm: *_“Không tự khoe khoang trong khi mình thiếu đức”_*, đó là lối sống khiêm tốn của những bậc Hiền Thánh; người thế gian không thể làm được. Người thế gian hễ làm được những gì thì khoe khoang không hết lời.
- Nếu sống với đức hạnh thứ sáu: *_“Không kết bạn với những người xấu ác”_*. Người xưa thường nói: “Chọn bạn mà chơi”. Đúng vậy! Gần mực thì đen, gần đèn thì sáng; chơi với những người bạn xấu ác thì sẽ ảnh hưởng xấu và tai tiếng xấu. Đây là một đức hạnh rất cần thiết cho sự giao tiếp với mọi người, trong cuộc sống chung đụng trong gia đình và xã hội.
- Nếu sống với đức hạnh thứ bảy: *_“Thích ở một mình nơi rừng núi thanh vắng”_*; đây là đức hạnh của những bậc tu hành chân chánh, sống nơi rừng núi thanh vắng, bởi tu hành nơi rừng núi thanh vắng thì mới xả tâm, ly dục ly ác pháp trọn vẹn.

Tóm lại, người muốn tu hành giải thoát thì phải sống trọn vẹn bảy đức hạnh này; muốn sống đúng bảy đức hạnh này thì phải tu tập hết sức, chớ không phải là lời nói suông, vì nói thì rất dễ, nhưng sống được với bảy đức hạnh này là một công trình tu tập. Người ta thường nói đức hạnh, nhưng người ta không thể sống với đức hạnh này ngay liền được. Nói thì dễ, nhưng làm rất khó, *bởi BẢY ĐỨC HẠNH này đã xác định được sự LY DỤC, LY ÁC PHÁP của một tu sĩ giải thoát, vì thế quý vị nên lưu ý!*

[.text-right]
_(Trích “Mười Hai Cửa vào Đạo”)_
[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== CHỨNG ĐẠO CỦA PHẬT GIÁO
[discrete]
=== Bức Tâm Thư Của Thầy Ngày 18-05-2009

Kính gửi các con! Một lần nữa Thầy nói về CHỨNG ĐẠO. Các con đừng cho rằng tu hành theo Phật giáo là không chứng đạo. Chứng đạo là một sự thật của Phật giáo. Phật giáo là một tôn giáo vì loài người, cho nên tu hành phải có CHỨNG ĐẠO. Phật giáo là một tôn giáo luôn luôn biết dùng tự lực của mình vượt lên mọi đau khổ của cuộc đời, vì vượt lên mọi khổ đau của cuộc đời nên CHỨNG ĐẠO. Một tôn giáo nhờ vào tha lực của Thần, Thánh, Tiên, Phật, Trời, Bồ Tát cứu khổ, cứu nạn, giải trừ bệnh tật, tai ách khổ đau của mình là một tôn giáo mê tín.

Mục đích của đạo Phật là làm chủ SINH, GIÀ, BỆNH, CHẾT, cho nên người nào làm chủ được SINH, GIÀ, BỆNH, CHẾT là người CHỨNG ĐẠO. Vì thế đạo Phật là đạo TỰ LỰC chứ không phải đạo THA LỰC. Ai tu theo Phật giáo mà cầu cúng, lạy lễ van xin TAM BẢO gia hộ là theo ngoại đạo Bà La Môn.

Đạo Phật còn gọi là đạo GIẢI THOÁT, vì thế ai sống đúng đạo đức không làm khổ mình, khổ người và khổ tất cả chúng sinh là CHỨNG ĐẠO. Bởi không làm khổ mình, khổ người và khổ tất cả chúng sinh đó là GIẢI THOÁT; mà giải thoát là CHỨNG ĐẠO. Sự chứng đạo của Phật giáo không có khó khăn, không có mệt nhọc; chỉ cần chịu khó học tập đạo đức nhân bản - nhân quả, sống với PHÁP TRÍ ĐẠO ĐỨC và TÙY TRÍ ĐẠO ĐỨC là có sự giải thoát ngay trước mặt; có sự GIẢI THOÁT ngay trước mặt là CHỨNG ĐẠO.

Muốn làm sáng tỏ sự CHỨNG ĐẠO các con đừng giải thích theo chữ Hán (Trung Hoa): đạo là con đường, nẻo, lối đi... Giải thích như vậy không đúng nghĩa Phật giáo. Vì “ĐẠO” ở đây có nghĩa là tâm không còn khổ đau, tâm được yên ổn an vui, tâm bất động không còn một ác pháp nào làm cho tâm động. Những điều trên đây tâm đã đạt được thì mới gọi là GIẢI THOÁT; mà giải thoát là CHỨNG ĐẠO như trên đã nói. Khi nói đến CHỨNG ĐẠO thì đức Phật dùng một cụm từ chỉ cho chúng ta thấy sự CHỨNG ĐẠO: *_“Sanh đã tận, phạm hạnh đã thành, các việc làm đã làm xong, không còn trở lui trạng thái này nữa”_*. Cụm từ này chỉ rất rõ sự GIẢI THOÁT:

1. SANH ĐÃ TẬN, có nghĩa là cuộc sống không còn đau khổ.
2. PHẠM HẠNH ĐÃ THÀNH, có nghĩa là đời sống giới luật đức hạnh nghiêm chỉnh.
3. CÁC VIỆC LÀM ĐÃ LÀM XONG, có nghĩa là sự tu tập đã hoàn tất, không còn tu tập một pháp môn nào nữa.
4. KHÔNG CÒN TRỞ LUI LẠI TRẠNG THÁI NÀY NỮA, có nghĩa là tâm không còn tham, sân, si, mạn, nghi nữa.

CHỨNG ĐẠO có nghĩa là giải thoát hoàn toàn, tâm không còn tham, sân, si, mạn, nghi như trên đã nói. Cho nên trong kinh Tương Ưng có đoạn ông Xá Lợi Phất hỏi Phật: *_“Bạch Thế Tôn! Nếu con được hỏi: này Hiền giả, giải thoát như thế nào mà Thế Tôn tuyên bố đã được chứng đắc, sanh đã tận, phạm hạnh đã thành, các việc làm đã làm xong, không còn trở lui lại trạng thái này nữa? Thì con sẽ trả lời: do tự giải thoát, do tự đoạn diệt tất cả các chấp thủ, do tự làm tâm con luôn an lạc trong chánh niệm; nhờ sống an lạc trong chánh niệm như vậy, các lậu hoặc không còn tiếp tục rỉ chảy và không còn tự chấp tự ngã”._*

Ngài Xá Lợi Phất trả lời rất đúng. Sự giải thoát này phải do chính mình, không có một người nào giúp mình được. Do tự chính mình phải ĐOẠN DIỆT CÁC CHẤP THỦ và phải luôn luôn SỐNG AN TÂM TRONG CHÁNH NIỆM, nhờ vậy mọi ác pháp không còn tác động được tâm. Để xác định sự CHỨNG ĐẠO, một lần nữa kinh Tương Ưng dạy: *_“Tóm lại, pháp môn này gọi tắt như sau, những cái gì được vị Sa môn gọi là lậu hoặc là Ta không còn nghi ngờ gì nữa, chúng đã được Ta diệt tận không còn phân vân gì nữa”_*. _(Tương Ưng tập 2)_

Đọc những lời trên đây, ai còn phủ nhận đạo Phật không CHỨNG ĐẠO?

Đức Phật xác định rõ cho chúng ta biết thế nào là PHÁP TRÍ: *_“Này các thầy Tỳ kheo, vị Thánh đệ tử biết già chết như vậy, biết già tập khởi như vậy, biết già diệt như vậy, biết con đường đưa đến già chết diệt như vậy. Đây là PHÁP TRÍ của vị ấy. Vị ấy với pháp này được thấy, được biết, được quả tức thời, được đạt đến, được thể nhập hướng dẫn thái độ của mình đối với quá khứ và trong tương lai”_*. Người có trí tuệ về các PHÁP của đời sống con người thì phải thông suốt GIÀ, CHẾT. Thông suốt GIÀ, CHẾT thì được gọi là PHÁP TRÍ.

1. GIÀ là cơ thể suy nhược, răng rụng, da nhăn, tóc bạc, lưng khọm, tay chân run rẩy, yếu đuối... Đó là một sự đau khổ của kiếp người.
2. CHẾT là cơ thể bị hủy diệt, tử vong, các uẩn tàn lụi, hoại diệt... Đó là một sự đau khổ mà con người không ai tránh khỏi.

Do thông suốt sự đau khổ ấy, nên người có trí phải lo tu tập làm chủ GIÀ, CHẾT. Một lần nữa, đức Phật dạy: *_“Này các thầy Tỳ kheo, vị Thánh đệ tử biết già chết như vậy, biết già tập khởi như vậy, biết già diệt như vậy, biết con đường đưa đến già chết diệt như vậy”_*.

Một khi đã hiểu biết như vậy, thì chúng ta cố gắng tu tập để giữ gìn tâm bất động; do giữ gìn tâm bất động thì lậu hoặc hoàn toàn sẽ bị diệt sạch. Cho nên kinh Tương Ưng xác định một lần nữa để chúng ta hiểu rõ sự GIẢI THOÁT bằng PHÁP TRÍ: *_“Đây là PHÁP TRÍ của vị ấy. Vị ấy với pháp này được thấy, được biết, được quả tức thời, được đạt đến, được thể nhập hướng dẫn thái độ của mình đối với quá khứ và trong tương lai”_*. _(Tương Ưng tập 2)_

PHÁP TRÍ là trí tuệ hiểu biết về các pháp sinh, già, bệnh, chết là khổ. Người có pháp trí hiểu biết cuộc đời này là khổ, không có vật gì trên thế gian này là ta, là của ta nên buông xả sạch, vì thế họ được giải thoát hoàn toàn.

Khi một người có PHÁP TRÍ, nên về tương lai có xảy ra điều gì họ chẳng lo lắng buồn phiền và sợ hãi; do chẳng còn buồn phiền và sợ hãi, nên họ được giải thoát. Đó là họ đang sống trong TÙY TRÍ. Bởi người có TÙY TRÍ là người giải thoát về tương lai. Đây, chúng ta hãy nghe đức Phật dạy: *_“Những Sa môn hay Bà la môn nào trong tương lai sẽ hiểu rõ già chết, sẽ hiểu rõ già chết tập khởi, sẽ hiểu rõ già chết diệt, sẽ hiểu rõ con đường đưa tới già chết diệt, tất cả những vị ấy sẽ hiểu biết như vậy. Như vậy, như hiện nay Ta vậy. Đây tức là TÙY TRÍ của vị ấy”_*.

Tóm lại, người có PHÁP TRÍ và TÙY TRÍ là người đang sống trong ba thời quá khứ, hiện tại và vị lai hoàn toàn thân tâm họ được giải thoát, không còn một chút xíu nào lậu hoặc. Người ấy được nhập lưu, nhập vào dòng Thánh, được đầy đủ Trí Hữu Học, được đầy đủ Minh Hữu Học. Một lần nữa, để xác định điều này, đức Phật đã dạy: *_“Này các thầy Tỳ kheo! Vì rằng vị Thánh đệ tử được thanh tịnh và thuần tịnh hai loại trí: PHÁP TRÍ và TÙY TRÍ. Vị ấy được gọi là Thánh đệ tử đạt tri kiến, đã đi đến diệu pháp này, đã chấp nhận diệu pháp này, đã đầy đủ hữu học trí, đã đầy đủ hữu học minh, đã nhập được pháp lưu, là bậc Thánh minh đạt tuệ, đã đứng gõ vào cửa bất tử”_*. _(Tương Ưng tập 2)_

Trong lời dạy này chỉ định rất rõ, người có đầy đủ PHÁP TRÍ và TÙY TRÍ là người hoàn toàn làm chủ sinh, già, bệnh, chết, cho nên lời dạy trong đoạn kinh này rất rõ ràng họ là người đã đứng gõ vào cửa BẤT TỬ.

Thầy xin ghi lại lời Phật dạy, để minh chứng rằng sự giải thoát của Phật giáo bằng sự hiểu biết mà đức Phật gọi là PHÁP TRÍ và TÙY TRÍ. Cho nên CHỨNG ĐẠO không phải chứng bằng THIỀN ĐỊNH như mọi người nghĩ, mà chứng đạo bằng PHÁP TRÍ và TÙY TRÍ.

[.text-center]
_Kính ghi_ +
_Trưởng lão Thích Thông Lạc_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== GIỚI - ĐỊNH - TUỆ
[discrete]
=== Bức Tâm Thư Cuối Cùng Của Thầy 
[discrete]
=== Ngày 01-12-2012

Kính gửi các con! Hôm nay, Thầy có vài lời nhắc nhở đến các con.

Trước tiên, Thầy xin nhắc lại 3 điều kiện hết sức quan trọng trong cuộc đời tu hành của người tu theo Phật, hay đến với Tu viện Chơn Như.

*icon:asterisk[] Điều thứ nhất:* Khi đến với đạo Phật, thì các con đã hiểu “Đạo Phật là Đạo Giải Thoát”. Vậy giải thoát như thế nào? - Đây, các con hãy lắng nghe lời Phật dạy: *_“Cạo bỏ râu tóc, đắp áo cà sa, sống không gia đình, ba y một bát, đời sống trắng bạch như vỏ ốc, tâm hồn phóng khoáng như hư không...”_*. Cho nên, khi đến với Tu viện Chơn Như thì các con phải sống đúng 3 hạnh: Ăn, Ngủ, Độc Cư; 3 đức: Nhẫn Nhục, Tùy Thuận, Bằng Lòng; đời sống Thiểu Dục, Tri Túc (ít muốn, biết đủ); chấp nhận đời sống Giới Hạnh, quyết tâm bằng mọi cách không để vi phạm một lỗi nhỏ nhặt nào. Đây chính là GIỚI.

*icon:asterisk[] Điều thứ hai:* Con đường tu tập giải thoát của đạo Phật không cần phải tu tập nhiều pháp. Đây, các con hãy lắng nghe lời Phật dạy: *“Bí quyết thành tựu của đạo Phật chỉ có hai điều kiện quan trọng nhất:*

1. _Giữ tâm không phóng dật._
2. _Thích sống nhàn tịch, độc cư, trầm lặng một mình”._

Để thực hiện được hai điều kiện này, Thầy đã chỉ dạy cho các con cách thức tu tập các pháp hành: Phòng hộ sáu căn, Như Lý Tác Ý, Tứ Chánh Cần, Tứ Niệm Xứ, Thân Hành Niệm, từ Nhiếp Tâm cho đến An Trú Tâm. Đó là những phương tiện tu tập, phải thiện xảo khéo léo áp dụng đúng thời, đúng lúc thì mới giúp các con sống an ổn một mình, không còn chướng ngại. Đây chính là ĐỊNH.

*icon:asterisk[] Điều thứ ba:* Đạo Phật là đạo Trí Tuệ, là sự hiểu biết của ý thức hay còn gọi là Tri Kiến Giải Thoát. Đức Phật dạy: *_“Những ai có Giới hạnh, an trú không phóng dật, Chánh trí, chơn Giải thoát...”_*. Khi một người tu sĩ hay cư sĩ theo đạo Phật mà sống trọn vẹn trong giới luật, và an trú tâm không phóng dật, thì người đó đã thành Chánh Giác. Đây chính là TUỆ. Và đức Phật đã khẳng định rằng: *_“Giới hạnh là Trí tuệ, Trí tuệ là Giới hạnh”_*.

Cho nên, con đường chứng đạo không ngoài “Giới - Định - Tuệ”. Giới giúp tâm buông xả ly dục ly ác pháp. Định giúp tâm an lạc sáng suốt. Trí hiểu biết rộng lớn không bị bất kỳ một pháp nào chi phối hay còn gọi là Tuệ Giải Thoát.

Đường đi quá rõ ràng, Thầy đã vạch sẵn cho các con thấy tu hành không phải khó. Khó là chỗ các con không bền chí, không gan dạ, thiếu nghị lực, không chịu buông bỏ tâm đời thường thế gian. Vì vậy mà trải qua bao năm tháng tu tập, các con cứ giậm chân tại chỗ và phạm phải những nội quy của Tu viện:

1. Ly gia cắt ái: lìa bỏ gia đình, không còn luyến ái. Vậy mà các con có giữ được đâu! Cứ tu được năm ba bữa, một vài tháng thì xin về thăm nhà hay xin điện thoại thăm gia đình. Đã vậy, có người dù đã nộp điện thoại nhưng vẫn còn lén lút sử dụng điện thoại riêng (thiếu đức thành thật).
[unstyled]
. Khi có người thân, họ hàng, con cháu, bạn bè đến thăm thì mau mau ra gặp. Các con không dám mạnh mẽ dứt khoát từ chối; phạm giới, phá hạnh độc cư.
2. Cạo bỏ râu tóc: khi các con thấy râu tóc ra dài là cạo được rồi, đâu cần phải chờ đúng 14, 15 hoặc 28, 29, 30. Đợi cho đúng ngày thì phải xem lịch, không có lịch thì hỏi người này hỏi người kia để biết mà cạo tóc... Thậm chí phá độc cư bằng cách ném thư qua cửa sổ, ra dấu, ra hiệu đủ mọi cách làm mất oai nghi chánh hạnh.
[unstyled]
. Riêng người cư sĩ thì chỉ cần giữ gìn đầu tóc cho gọn gàng, có đâu tóc kẹp kiểu này kiểu kia, cột dài cột ngắn như trẻ con hoặc là xõa tóc làm đẹp; phạm giới trang điểm, làm đẹp.
3. Ba y một bát: là một y hạ, y trung, y thượng và một bình bát để xin ăn. Thời xưa đức Phật còn phải lượm vải thây ma để mặc, bây giờ Thầy cho các con mặc đồng phục mỗi người 2 bộ (người nữ được 3 bộ), và một áo tràng là đủ để mặc hằng ngày. Thế mà có người chê đồ cũ đồ mới; có người lại sửa sang, kết, đính thêm nút không giống ai; lại để dành hai, ba bộ; còn áo tràng thì hai, ba cái; phạm vào giới cất giữ.
[unstyled]
. Cái bát là để đi xin ăn. Người tu sĩ ăn trong bát, uống trong bát. Thế mà các con có người chê khen bát này lớn, bát kia nhỏ; bát này nặng, bát kia nhẹ. Thậm chí, có người đi khất thực chỉ mang cái nắp bát, rồi ăn luôn trên cái nắp bát hoặc ăn luôn trong mâm. Người thì lấy thêm chén nhỏ để sớt cơm ra ăn riêng chứ không ăn trong bát. Đức Phật ví cái y như đôi cánh, cái bát như cái mỏ con chim. Vậy là “con chim không cần cái mỏ”; các con quá xem thường giới hạnh!
4. Trước kia Thầy có dạy các con nuôi dưỡng tâm từ bằng cách là đến giờ thọ thực, khi thấy có chúng sinh trước mắt các con, chúng đang đói khát tìm thức ăn sinh sống, thì khi ấy chúng ta mới hy sinh và chia sẻ thực phẩm do mình vừa đi xin về, để sớt một ít mang cho chúng trước khi mình dùng. Đằng này các con hiểu sai lời Thầy dạy, lấy của đàn na cho dư thừa để rồi đi tìm chúng sinh mà bố thí. Có người cất giữ thực phẩm cho đến chiều rồi mang đi nơi khác chờ cho chó, mèo, chim, sóc... đến ăn. Nếu chúng không đến thì coi như thực phẩm ngày hôm ấy bị bỏ phí, thiu mốc.
[unstyled]
. Các con là những người tu hành, tu thì không xong, cũng không làm gì ra tiền, cho nên các con không biết quý trọng công sức cúng dường bằng mồ hôi nước mắt của những người khác. Họ cúng dường là chỉ mong hưởng được công đức tu hành của các con. Các con có nghĩ đến điều này hay không? Các con có xứng đáng hay chưa? Thật là thiếu trí tuệ và phí phạm!
5. Thiểu dục tri túc: ít muốn biết đủ. Các con thì sao? Nhìn hết trong Tu viện, Thầy thấy rất ít người sống được hạnh này. Người nào cũng muốn dư, không muốn đủ; thậm chí sử dụng 2, 3 đôi dép; đi dép trong, dép ngoài; vớ thì hai, ba đôi; bàn chân suốt ngày không lìa đôi vớ; nón thì kiểu này, kiểu nọ; ở trong thất thì đeo khẩu trang, mang kính mát; khăn lớn, khăn nhỏ phơi đầy sào; đi đâu gặp cái gì cũng lượm mang về thất từ một cục gạch, đoạn dây, khúc nhựa, cái lọ, keo hũ, bọc giấy, bao bì, vv... lại còn sinh niệm chế ra cây phất trần phẩy qua phất lại như mấy ông Tiên; ngồi thì kê chân kê mông, lót nệm lót gối để cho êm ái. Trong và ngoài thất các con ở nào là giàn, là kệ, dây sào, v.v... tất cả bày biện, treo móc, giăng mắc... coi chẳng ra gì, y như một cái quầy hàng xén. Cuộc đời tu hành mỗi ngày người ta buông xả xuống, còn các con mỗi ngày mỗi ôm vô thì làm sao cuộc sống của các con “trắng bạch như vỏ ốc”, tâm hồn các con “phóng khoáng như hư không”. Thật là hổ thẹn!
6. Khuya dậy thì không đúng giờ (trễ 5 - 10 phút); mùng, mền không xếp gấp gọn gàng; thức thì không tỉnh táo, ưa thích ngồi cho an, mắt nhắm lim dim ngồi gục tới gục lui; lại còn chế pháp đưa tay lên xuống, qua lại như người đang múa, không oai nghi chút nào; đi kinh hành thì lười biếng sợ mỏi chân, sợ lạnh... thích nuôi dưỡng cái thân. Thật là quá tệ!
7. Tu hành thì phải tự mình tư duy triển khai tri kiến trí tuệ để vượt lên những chướng ngại. Mỗi lần như vậy trí lực của các con càng mạnh mẽ, vững chãi hơn, nhanh nhẹn sáng suốt hơn. Cớ sao các con lại để tâm trí mình thụ động, liệt tuệ, chỉ còn biết vay mượn tạm bợ tri kiến của người khác. Thầy cho người đến nhắc nhở, hướng dẫn giúp các con tháo bỏ những vấn đề dính mắc mà xả tâm, để rồi tiếp tục an trú tu tập. Trái lại, các con thích hội họp, thích nói chuyện cho vui và hỏi những chuyện đâu đâu không lợi ích, hỏi ngoài tầm hiểu biết của con người (hỏi về cõi chết). Đây cũng là cách thức phá độc cư; dù có tu ngàn đời mãi mãi các con cũng không thấy đạo. Thật là vô bổ!

Tất cả những điều Thầy đã nêu trên các con hãy tự kiểm điểm lại mình, phải lượng sức mình cho kỹ. Vào Tu viện Chơn Như mà không chịu xả bỏ dục lạc thế gian thì tu tập có ích lợi gì hỡi các con! Nếu không đủ khả năng, Thầy khuyên các con hãy trở về với gia đình sống lợi ích cho con cho cháu. Chứ ở Tu viện mà phạm giới, phá giới thì Thầy không thể giúp gì được cho các con, ngược lại, các con phải mang nợ đàn na tín thí, trả biết bao giờ cho hết.

Thầy đề nghị Ban Quản lý thường xuyên kiểm tra xem xét từng khu vực. Tu sinh nào vi phạm Thanh Qui của Tu viện lần thứ nhất được nhắc nhở, lần thứ hai còn tái phạm thì chuyển ngay ra Khu Tiếp nhận để quý sư hướng dẫn thêm. Nếu vẫn vi phạm không sửa, tốt hơn chúng ta mời họ ra về. Đây là chúng ta thương họ, chớ không phải thiếu tình người đâu các con ạ!
Sau cùng, Thầy có lời khuyên đến tất cả các tu sinh đang có mặt tại Tu viện Chơn Như: *_“Nếu các con không tu thì thôi, còn quyết tâm tu hành thì phải có ý chí nghị lực vứt bỏ những thứ tầm thường của thế gian, sống đúng trọn vẹn trong giới hạnh, nhất định không vi phạm một lỗi nào. Hãy cố gắng vượt lên làm Thánh các con ạ! Để trở thành những đệ tử ưu tú của Thầy, xứng đáng là những tu sĩ, cư sĩ của Phật giáo”_*.

[.text-center]
_Kính ghi_ +
_Thầy của các con_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TÂM THƯ GỬI QUÝ Phật tử
[.text-right]
[discrete]
=== Tu viện Chơn Như, ngày 26/04/2018

Kính gửi: Quý Phật tử trong nước và ở nước ngoài

Kính thưa quý vị: Do nhân duyên gần đây Phật tử có những điều thắc mắc, vì vậy hôm nay Mật Hạnh xin có đôi lời kính gửi đến quý vị, với niềm mong ước mọi người cùng đoàn kết, tinh tấn trên con đường tu học giải thoát, cùng hướng về từ trường tâm bất động thanh thản, an lạc, vô sự, của đức Phật và đức Trưởng lão Thích Thông Lạc.

Chỉ có tâm bất động thanh thản, an lạc, vô sự là cứu cánh giải thoát, là đạo đức thương mình thương người, xin quý vị nhớ mãi đừng quên!

Dấu chân tăng đoàn đức Phật và Trưởng lão vẫn còn đâu đây, thời ấy tăng chúng sống gần quanh đức Phật; 1250 vị tỳ kheo cùng đi khất thực, thọ trai, nghe pháp rồi giữ miên mật giới luật tu hành cho đến khi Phật nhập Niết bàn, và sau đó khi ngài A Nan nhập Niết bàn, từ đây mới sinh ra nhiều hệ phái khác nhau, chia nhỏ và bẻ vụn giới luật.

Nhưng các Tổ đâu biết rằng giới luật ở đâu là trí tuệ ở đó, hay giới luật ở đâu thì tri kiến giải thoát ở đó. Đức Trưởng lão dạy nhẫn được việc khó nhẫn, làm được việc khó làm là những điều đáng ca ngợi.

Khó nhưng mà không khó, nếu chúng ta quyết tâm buông bỏ thì khó khăn sẽ được hóa giải, hương vị giải thoát ngay trước mắt, (pháp ta không có thời gian đến để mà thấy).

Hiện nay có ít nhóm nhỏ phân chia thành bè phái nhóm họp manh mún với nhiều nguyên do.

Xưa đức Phật đã dạy: “Chớ có tin và nghe người ta nói đồn, chớ có tin vì nhân lý luận siêu hình, chớ có tin vì đúng theo một lập trường, chớ có tin vì đánh giá hời hợt những dự kiện, chớ có tin vì phù hợp với định kiến của mình, chớ có tin vì nơi xuất phát có uy quyền”... Như vậy quý vị đang mất quá nhiều thời gian không lợi ích cho mình và người, không những thế còn làm yếu đi sự khích lệ sách tấn tu tập giữa bạn đồng môn nữa.

- Được thân người là khó, gặp được chánh pháp của Phật Thích Ca Mâu Ni là điều vô cùng khó hơn nữa! Sau hơn 2500 năm đức Trưởng Lão là người duy nhất tìm lại được đường lối tu tập làm chủ sanh, già, bệnh, chết và chấm dứt tái sanh luân hồi. Cả cuộc đời Ngài đã tu tập cần khổ không hề lơi lỏng, suốt mười năm sống độc cư miên mật cho đến khi đọc được Đại tạng kinh Nikaya (do HT Thích Minh Châu dịch) Ngài đã dùng pháp Như Lý Tác Ý quét sạch tham sân si vi tế. Cuối cùng là người chiến thắng giặc sanh tử, ca khúc khải hoàn, và từ đây Ngài đã kiên quyết chỉ dạy truyền trao kinh nghiệm thực chứng làm chủ sanh, già, bệnh, chết, còn để lại đầy đủ tư liệu băng giảng và 28 đầu sách cho chúng ta và các thế hệ mai sau.

Đức Trưởng lão khi còn sống đương thời cho đến lúc nhập niết bàn vẫn ở trong từ trường của tâm bất động thanh thản, an lạc và vô sự mà đức Phật và chúng Thánh tăng đang ở đó. Do vậy, dù Trưởng lão đã nhập niết bàn nhưng đức Thầy vẫn luôn bên cạnh chúng ta, là tâm bất động thanh thản.

Tri ân công đức của đức Phật và Trưởng lão, từ đây chúng ta hãy cố gắng trau dồi đức đoàn kết hiếu sinh đa hướng, nguyện triển khai tri kiến giới luật đức hạnh nhân bản và nhân quả, hằng ngày sống không làm khổ mình không làm khổ người và không làm khổ chúng sanh bằng đức hiếu sinh đa hướng. Bất cứ một pháp nào đến chúng ta đều đem lòng yêu thương và tha thứ bằng thân hành, khẩu hành, ý hành. Có như vậy mới thương mình đúng cách và trao lòng yêu thương chân thật giải thoát đến với mọi người.

Kính thưa quý vị!

Mỗi con người chúng ta ai cũng có trách nhiệm và bổn phận, nhưng trách nhiệm và bổn phận của mỗi chúng ta dù nam hay nữ đều phải sống có đạo đức (không làm khổ mình khổ người, không làm khổ chúng sanh) nhờ sống có đạo đức mới đem lại sự bình an, yên vui cho mình, cho người và cho mọi vật. Vì vậy quý vị nên biết chính trách nhiệm và bổn phận đạo đức của con người là trên hết, không có trách nhiệm bổn phận nào ngoài đạo đức quý vị à!

Cá nhân có đức hạnh đoàn kết hiếu sinh đa hướng thì luôn thấy lỗi mình để sửa.

Là cư sĩ sống đúng năm giới đức làm người, hành trong mười điều lành, sống với đức cần lao buông xả, nhưng trên đời này người sống siêng năng cần lao thì ít, người lười biếng ăn không ngồi rồi thì nhiều, khi đi ra làm việc thì tránh công việc nặng nhọc tìm công việc nhẹ nhàng, tìm chỗ ngồi chơi. Làm người ai cũng có sự sống như ai, vì thế ai cũng phải siêng năng làm việc, có làm việc mới có sự sống công bằng, còn không làm việc mà có sự sống thì sự sống không công bằng, chỉ là cướp công cướp của của người khác, bởi vậy không siêng năng làm việc thì không xứng đáng làm người. Con ong, con kiến còn siêng năng làm việc quần quật suốt cả ngày huống chi chúng ta là con người thì phải tích cực siêng năng trong việc làm cùng chia sẻ nặng nhọc với mọi người trên hành tinh này.

Nếu chúng ta sống như vậy thì đâu có thời gian đi đây đi đó, tụ họp nói chuyện tào lao, bàn chuyện người khác. Luôn tích tập thời gian sống với tâm thanh thản an lạc và vô sự.

Gia đình có đoàn kết hiếu sinh đa hướng thân hành, khẩu hành, ý hành là gia đình hạnh phúc nhứt trên thế gian này.

Luôn an vui êm ấm, mỗi phút giây luôn chia sẻ, đỡ đần công việc giữa ông bà, cha mẹ và con cái, hay anh chị em đùm bọc lẫn nhau, giúp nhau trong học tập cũng như trong nghề nghiệp, cùng đồng chí hướng đạo đức giải thoát sách tấn tu tập, đồng cam cộng khổ. Vì cuộc sống chung nên cùng vượt qua chướng ngại nhờ tri kiến giải thoát đức hiếu sinh. Cho nên đức hiếu sinh thường biểu hiện qua hành động thương mình, thương người bằng sự suy nghĩ; yêu thương bằng hành động cung kính, êm ái nhẹ nhàng; bằng ngôn ngữ ôn tồn nhã nhặn, ái ngữ êm dịu. Đó là đức hiếu sinh bố thí trên tất cả sự bố thí mà quý vị hãy ghi nhớ đừng quên, luôn luôn áp dụng vào cuộc sống hàng ngày để gia đình được an vui hạnh phúc.

Chính nhờ vậy thì mỗi tập thể là nhóm Phật tử Nguyên thủy của mỗi tỉnh, thành đại diện cho một xã hội thu nhỏ luôn vững mạnh về mọi mặt nhờ đức đoàn kết hiếu sinh đa hướng. Nhóm Phật tử Nguyên thủy có tinh thần kết nối yêu thương đa hướng, nhiều gia đình cư sĩ tích cực hỗ trợ phát triển kinh tế bằng nghề nghiệp chân chính, tạo ra các sản phẩm có giá trị có lợi ích cho mình, cho mọi người.

Ở đâu có đoàn kết là ở đó có thành công, “Đoàn kết, đại đoàn kết, thành công, đại thành công”.

Trên đây là những lời vàng ngọc của đức Phật, đức Thầy đã để lại cho chúng ta, xin quý vị hãy khắc cốt ghi tâm để tu tập được giải thoát trong cuộc đời đầy đau khổ.

Bản thân Mật Hạnh cũng đã từng sống độc cư 3 năm và đã nhìn thấy sự giải thoát của đạo Phật rất thực tế, rõ ràng không có mơ hồ. Mật Hạnh luôn ước ao giữ gìn mạng mạch Chánh pháp để cho con cháu sau này biết được con đường chánh pháp giải thoát của đạo Phật, để đem lại lợi ích và hạnh phúc cho con người, đem lại nền đạo đức Nhân bản - Nhân quả, sống không làm khổ mình khổ người và không làm khổ tất cả chúng sanh - đó là tâm nguyện của Mật Hạnh. Và mong ước của Mật Hạnh cũng mong mọi người hãy cùng đồng lòng chung sức với Tu viện.

Khi Thầy truyền trao trọng trách cho Mật Hạnh thì Mật Hạnh đã gặp biết bao nhiêu là gian nan, biết bao nhiêu sóng gió phũ phàng, quý vị có thấu chăng? Mật Hạnh chỉ biết cùng đồng lòng mọi người trong Tu viện và các quý Phật tử, chỉ biết thương yêu và tha thứ, không muốn giận hờn oán trách, nói xấu một ai hết, vì tất cả chúng ta đều vô minh, đều đáng thương cả. Chỉ ước mong quý vị đoàn kết yêu thương xây dựng Chánh pháp, đừng hơn thua với nhau khiến chúng ta thêm đau khổ. Cho nên Mật Hạnh chỉ biết vượt qua mọi thử thách, mọi gian lao, phải quyết không chùn bước.

Sau cùng Mật Hạnh xin gửi lời thăm chúc mọi người, kính chúc quý vị dồi dào sức khỏe, thân tâm thường an lạc và gặp được nhiều may mắn trên con đường tu tập đạo đức giải thoát.

[.text-center]
_Kính thư_ +
_Tỳ kheo Thích Mật Hạnh_ +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== TÂM THƯ GỬI CÁC CỤ, CÁC BÁC ĐANG AN DƯỠNG TẠI Tu viện CHƠN NHƯ

Kính thưa các cụ, các bác!

Sau khi đến thăm các cụ, các bác ở khu An Dưỡng, lúc trở về Mật Hạnh có nhiều trăn trở suy tư, nên xin gửi đến các cụ, các bác đôi dòng tâm huyết để khích lệ các cụ, các bác hãy giữ vững niềm tin và tinh tấn tu tập. Các bác ạ, thời gian trôi qua không bao giờ trở lại, do vậy các cụ, các bác hãy quý trọng từng giây, từng phút, từng giờ, hàng ngày siêng năng tu tập, luôn sống với tâm Bất động, Thanh thản, An lạc, Vô sự để vô thường đột ngột có mất thân thì có nơi trở về bình an trong từ trường thanh thản, không còn khổ đau, làm chủ sanh, già, bệnh, chết và chấm dứt tái sanh luân hồi.

Ai trong các cụ, các bác cũng đều biết tái sanh đầy đau khổ trùng trùng... Sinh ra, lớn lên, học hành để có nghề nghiệp, rồi già nua, run rẩy, bệnh này, tật khác... thấy rõ sáu trạng thái luân hồi hàng giờ, hàng ngày: vui buồn, đói khát, lo lắng, sân hận, tham lam, đố kỵ, ganh ghét ... Thử hỏi một ngày một đêm các cụ, các bác có được bao phút giây “thanh thản, an lạc, vô sự”???

Mật Hạnh sống gần bên đức Trưởng Lão, Mật Hạnh thấy rõ đức Thầy có từ trường bình an, thanh thoát lạ thường dù cho bất cứ hoàn cảnh nào xảy ra. Bao nhiêu công việc đến tay, nhưng đức Thầy bằng thân giáo luôn xử lý tốt đẹp. Thường khi ngồi chơi một mình, hay khi trả lời tâm thư Phật tử, lúc viết sách, khi đo đạc, cất thất cho tu sinh, khi trồng cây hay khi rửa chén, quét sân... đức Trưởng Lão luôn sáng suốt, cẩn thận kỹ lưỡng, dè dặt chánh niệm trong mọi thân hành. Có được như vậy là vì đức Trưởng Lão luôn sống trong giới luật, đức hạnh, luôn sống trong trạng thái an lạc, vô sự.

Đức Phật ngày xưa cũng vậy, Ngài cũng có thân, thân đức Phật cũng già cỗi, cũng có bệnh đau. Trong kinh Trường Bộ có chép lại một đoạn như sau: “Trong khi Thế Tôn an cư trong mùa mưa, một cơn bệnh trầm trọng khởi lên rất đau đớn, gần như muốn chết, nhưng Thế Tôn giữ tâm chánh niệm tĩnh giác chịu đựng cơn đau ấy, không một chút rên la (ta thán). Thế Tôn tự nghĩ: ‘Thật không hợp lẽ nếu ta diệt độ mà không có một lời với các đệ tử hầu cận ta, không từ biệt chúng tỳ kheo. Vậy ta hãy lấy sức tinh tấn nhiếp phục cơn bệnh này, duy trì mạng căn và tiếp tục sống’.

Rồi Thế Tôn lành bệnh, sau khi lành bệnh không bao lâu đức Phật rời khỏi Tịnh xá...” (Kinh Trường Bộ tập I, trang 582)

Như vậy rõ ràng đức Phật do từ các pháp môn tu tập mà làm chủ sống chết, bệnh tật. Ngày nay chúng ta cũng ngay trên các pháp môn này mà tu tập thì cũng làm chủ sống chết, bệnh tật, cũng có thể kéo dài tuổi thọ, sống chết tự tại như đức Phật ngày xưa.

Đức Trưởng Lão Thích Thông Lạc cũng vậy, sau khi chứng đạo năm 1980, ngài biết sự nghiệp tạo duyên giáo hóa chúng sanh đầy gian nan, đầy sóng gió, ngài đã làm việc suốt 21 tiếng trên ngày. Có những hôm Mật Hạnh chứng kiến Ngài viết sách hàng giờ đồng hồ liền, như hiểu được mạch cảm xúc dòng suy tư tâm huyết sách tấn Phật tử, Mật Hạnh không dám làm gián đoạn công việc của Ngài. Nhiều lúc thấy đức Thầy xong việc Mật Hạnh mới nhẹ nhàng và có lời thỉnh cầu: “Con xin bạch Thầy làm việc vừa sức, tuổi Thầy đã cao”. Nhưng Thầy nói: “Thầy không sao, con cứ yên tâm. Con phụ giúp công việc với Thầy, có nhiều khó khăn lắm, con cần dũng mãnh ráng vượt lên để cùng Thầy chấn hưng Phật pháp”. Nghe vậy Mật Hạnh càng thương Thầy nhiều hơn và tự nhắc mình phải siêng năng hơn nữa để không phụ tình thương yêu của Thầy.

Có những hôm mưa gió trở trời Thầy ho rất nhiều, những tiếng ho khan, liên tục không dứt như xé ruột gan, Mật Hạnh kề bên không làm sao được, chỉ có thể rót ly nước ấm, hay khoác chiếc áo cho Thầy khỏi lạnh. Rồi Thầy vỗ về: “Thầy không sao đâu con, con đừng lo!”.

Dường như lòng yêu thương đối với đệ tử và sự sống của muôn loài chúng sanh quá lớn đến vô lượng nên đức Trưởng Lão với thân gầy ốm, với những cơn ho kéo dài (vì sau chiến tranh Ngài chỉ còn có một lá phổi) Ngài đã nhập vào thiền định kéo dài mạng căn, đã làm nên những việc phi thường để hôm nay Phật tử có được đường lối tu tập đúng chánh pháp, giải thoát thân tâm ra khỏi sự trầm luân đau khổ của kiếp người.

Con người ai cũng phải trải qua những cơn bệnh đau, không nặng thì nhẹ, bệnh đau là không thể tránh khỏi.

Mật Hạnh cũng vậy, tuy chưa già lắm nhưng hàng ngày vẫn luôn chiến đấu với bệnh tật, những cơn đau vô thường đến đi, những cơn đau có lúc quặn thắt tưởng chừng không chịu nổi, nhưng nhờ pháp Như Lý Tác Ý mà Mật Hạnh đã vượt qua.

Có những bệnh chúng ta tác ý chưa vượt qua được thì chúng ta phải trợ phụ thêm thuốc men, nhưng tu tập tác ý đuổi bệnh là chính, uống thuốc chỉ là phụ thôi.

Sau cùng Mật Hạnh kính chúc các cụ, các bác luôn dồi dào sức khỏe, tinh thần vững vàng, thân tâm thường an lạc.

[.text-right]
_Tu viện Chơn Như, ngày 24 tháng 05 năm 2018_ +
_Kính thư_ +
_Tỳ kheo Thích Mật Hạnh_
[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== MẪU LỆNH TÁC Ý PHÁP THÂN HÀNH NIỆM

Tác ý thong thả, rõ ràng từng chữ; tác ý truyền lệnh xong, rồi thân mới thực hiện hành động theo:

[cols="^1,^1", frame=none, grid=none]
|===
|Tay trái để sau lưng!
|Hạ gót xuống!

|Tay phải để lên tay trái!
|*Chân phải (chuẩn bị) bước!*

|*Chân trái (chuẩn bị) bước!*
|Dở gót lên!

|Dở gót lên!
|Dở chân lên!

|Dở chân lên!
|Đưa chân tới!

|Đưa chân tới!
|Hạ chân xuống!

|Hạ chân xuống!
|Hạ gót xuống! . . .
|===

Đến bước thứ 20 thì thêm hành động *“Kéo chân về!”*, trước hành động *“Hạ chân xuống!”*, để hai bàn chân hạ xuống đứng ngang bằng nhau.

Khi đứng lại xong, thì tiếp tục truyền lệnh CÁCH THỨC NGỒI:

[cols="^1,^1", frame=none, grid=none]
|===
|Tay phải buông xuống!
|Chân phải duỗi ra!

|Tay trái buông xuống!
|Chân trái co lại xếp bằng!

|Tay trái đưa lên trước mặt!
|Chân phải co lại!

|Tay phải đưa lên trước mặt! 
|Tay phải nắm cổ chân phải!

|Hai chân co ngồi xuống!
|Đặt lên chân trái xếp bằng!

|Tay trái chống đất sau lưng!
|Tay phải đặt lên trước bụng!

|Tay phải chống đất sau lưng!
|Tay trái đặt lên tay phải!

|*Hạ thân ngồi (bệt) xuống!*
|*Lưng thẳng lên!*

|Chân trái duỗi ra!
|Mắt nhìn phía trước!
|===

Tiếp đó truyền lệnh ĐƯA TAY RA, VÔ:

[cols="^1, ^1", frame=none, grid=none]
|===
|Tay trái đưa ra! 
|Tay phải đưa ra! 

|Tay trái đưa vô! 
|Tay phải đưa vô!
|===

Như vậy là đưa ra, vô mỗi tay 1 lần. Tác ý đưa tay ra, vô 5 lần thì truyền lệnh CÁCH THỨC ĐỨNG LÊN:

[cols="^1, ^1", frame=none, grid=none]
|===
|Tay trái chống đất sát hông!
|Tay trái đưa ra trước mặt!

|Tay phải chống đất sát hông!
|(Hoặc chống gối trái)

|Chân phải duỗi ra!
|Tay phải đưa ra trước mặt!

|Chân trái duỗi ra!
|(Hoặc chống gối phải)

|Chân phải co gối lại!
|*Hai chân đứng lên!*

|Chân trái co gối lại!
|Tay trái hạ xuống!

|*Hai tay chống ngồi lên!*
|Tay phải hạ xuống!
|===

Khi đứng lên xong, quý tu sinh tiếp tục đi 20 bước vòng thứ 2... và cứ tu tập như vậy cho đến 30 phút thì xả nghỉ.
Pháp môn Thân Hành Niệm là giai đoạn tu tập Tỉnh Thức thứ tư, có công năng tỉnh thức rất cao, phá hôn trầm, thùy miên vô ký rất tuyệt vời. Pháp môn này đối với quý Phật tử còn nhiều gia duyên, *tâm ly dục, ly ác chưa tròn đủ thì không nên tu tập nhiều, vì tu tập nhiều sẽ rơi vào các loại tưởng thì rất nguy hiểm*, sẽ rối loạn thần kinh, thành tẩu hoả nhập ma, đó là một loại bệnh điên. Xin quý Phật tử lưu ý: _“Chỉ tu tập 30 phút mà thôi!”._

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== NHỮNG BÀI KỆ “BUÔNG XUỐNG ĐI!”

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Chớ giữ làm chi, có ích gì. +
Thở ra chẳng lại, còn chi nữa? +
Vạn pháp vô thường, buông xuống đi!

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Chớ giữ làm chi, có ích gì? +
Ôm vào đau khổ vô cùng tận, +
Buông xuống ngay liền vạn khổ đi!

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Chấp giữ thân tâm có ích gì? +
Thở ra chẳng lại, còn chi nữa? +
Thân tâm vô thường, buông xuống đi!

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Trò đời như mộng, có còn chi? +
Tứ đại trả về cho tứ đại, +
Thanh thản, an nhàn lúc phân ly.

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Tâm hồn thanh thản, chẳng sầu bi. +
Cuộc đời ngắn ngủi trong chớp mắt, +
Còn có vui gì, chẳng bỏ đi?

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Chớ diệt ý thức, có ích gì? +
Ý làm chủ, dẫn đầu các pháp, +
Lợi ích vô cùng, sao bỏ đi?

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Tác ý đi, hãy tác ý đi! +
Bất động, thanh thản, chẳng sầu bi. +
Tác ý đi, còn lo chi nữa? +
Giải thoát đây rồi, tác ý đi!

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

Buông xuống đi, hãy buông xuống đi! +
Bất động, thanh thản, chẳng sầu bi. +
Buông xuống đi, còn lo chi nữa? +
Giải thoát đây rồi, buông xuống đi!

Trưởng lão Thích Thông Lạc

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]