= HƯỚNG DẪN NHẮC NHỞ TU SINH 
TRƯỞNG LÃO THÍCH THÔNG LẠC
:keywords: keywords, will, be, separated, by, commas 
:doctype: book
:sectlinks:
:icons: font


== NỘI QUY Tu viện CHƠN NHƯ

[upperroman]
. Tu sĩ và Phật tử tại Tu viện Chơn Như phải thực hiện đúng Nội quy của Tu viện và chấp hành đúng chủ trương, chính
sách của Đảng và pháp luật của Nhà nước, phải cung cấp đầy đủ các giấy tờ cần thiết trước khi vào tu học:
    - Chứng minh nhân dân/Căn cước công dân (bản gốc)
    - 01 bản Sơ yếu lý lịch (có địa phương xác nhận)
    - 03 tấm ảnh thẻ cỡ 4x6 hoặc 3x4 cm
    - Đơn phát nguyện xin đăng ký tu học (trường hợp này dùng cho những vị tu học trong thời gian dài)

. Tu sinh đến Tu viện tu tập phải chấp hành và thực hiện đúng các quy định đã được ghi rõ trong Thanh Quy Tu viện Chơn Như, cụ thể:
    1. Hãy tham khảo kinh sách và băng giảng của Trưởng Lão Thích Thông Lạc thật thông suốt trước khi đến Tu viện tu tập.
    2. Thực hiện đúng hạnh sống LỤC HÒA, 3 ĐỨC (Nhẫn nhục - Tùy thuận - Bằng lòng), 3 HẠNH (Ăn - Ngủ - Độc cư), cụ thể:
        - Ngày ăn một bữa, không được ĂN PHI THỜI.
        - Ngày được ngủ 5 giờ, gồm có trưa ngủ 1 giờ sau khi ăn; khuya được ngủ 4 giờ vào 10 giờ tối. Ngoài những giờ trên không được
        - SỐNG MỘT MÌNH, không được nói chuyện với bất kỳ một người nào (ngoại trừ những người quản lý Tu viện).

    3. Phải tu tập đúng theo đường lối của Tu viện Chơn Như là sống đúng đạo đức nhân bản - nhân quả: “Sống không làm khổ mình, khổ người và không làm khổ chúng sinh”, không được tu tập những pháp môn khác.
    4. Chấp hành nghiêm túc giờ giấc, tu tập theo thời khóa của Tu viện:
        - Từ 02h - 05h khuya: Tu tập “xả tâm, ly dục ly ác pháp”.
        - Từ 05h - 07h sáng: Nghỉ ngơi, vệ sinh cá nhân và khu vực sân thất.
        - Từ 07h - 10h sáng: Tu tập “xả tâm, ly dục ly ác pháp”.
        - Từ 10h - 14h trưa: Vệ sinh cá nhân, ăn trưa (khất thực) và ngủ trưa (1 tiếng).
        - Từ 14h - 17h chiều: Tu tập “xả tâm, ly dục ly ác pháp”.
        - Từ 17h - 19h tối: Nghỉ ngơi, vệ sinh cá nhân và khu vực sân thất.
        - Từ 19h - 22h tối: Tu tập “xả tâm, ly dục ly ác pháp”.
        - Từ 22h - 02h đêm: Ngủ nghỉ.
    5. Để thực hiện đúng hạnh “BA Y MỘT BÁT”, tu sinh đến tu tập không nên mang theo những vật dụng cá nhân không đúng quy định vào thất như: điện thoại, máy tính, máy ghi âm, máy nghe, v.v... Trường hợp có mang theo thì phải nộp lại cho Tu viện giữ gìn trong thời gian nhập thất tu tập.

. Tu sinh vào Tu viện tu tập, nếu không chấp hành và thực hiện đúng Thanh Quy Tu viện Chơn Như sẽ được mời rời khỏi Tu viện:
    - Vi phạm lần thứ nhất được nhắc nhở.
    - Vi phạm lần thứ hai tự phát lồ sám hối.
    - Vi phạm lần thứ ba phải tự giác rời khỏi Tu viện, không được ở lại với bất kỳ lý do nào.

Trên đây là một số quy định về tu tập tại Tu viện Chơn Như. Mong rằng quý tu sinh hãy thực hiện tốt những quy định này.

[.text-center]
Kính ghi +
Tu viện Chơn Như +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== CÁCH ĐI KHẤT THỰC VÀ THỌ THỰC (ĂN CƠM)

Kính gửi quý tu sinh! Đời người tu sĩ không làm một nghề nào khác, chỉ duy nhất sống bằng nghề xin ăn ngày một bữa
mà thôi. Bởi vậy, khi khất thực và thọ thực cần phải y áo trang nghiêm chỉnh tề, để bày tỏ lòng quý trọng và sự biết ơn công sức, tịnh vật của đàn na thí chủ. Vì có những người đến Tu viện tu tập chưa biết cách thức đi khất thực và thọ thực như thế nào, nên chúng tôi tạm ghi ra hướng dẫn này để giúp mọi người cùng thực hiện cho đúng cách như sau:

=== CÁCH ĐI KHẤT THỰC:
1. Phải mặc áo tràng (áo giới) cho nghiêm chỉnh, cổ áo phải ngay ngắn, kín đáo.
2. Tay trái đỡ dưới bát và tay phải ôm vòng bát.
3. Trước khi ra khỏi thất, đứng nghiêm chỉnh rồi tác ý: “Xin tất cả chúng sinh hãy tránh ra, đừng nằm trên bước đường tôi đi”.
4. Khi bước đi lưng thẳng, mắt nhìn xuống phía trước, tỉnh giác để tránh giẫm đạp lên ốc, kiến, trùn, cuốn chiếu và các côn trùng nhỏ bé khác...
5. Phải đi đường thẳng, đường lớn dẫn đến nơi khất thực, không được đi đường tắt ngang qua thất người khác.
6. Không nên đi từng bước chậm rãi như người đau bệnh, cũng không nên đi nhanh quá; nên đi bình thường, nhẹ nhàng, khoan thai.
7. Khi đến kệ cơm, đặt bát xuống, giở nắp mâm xem thức ăn để xới cơm vừa đủ ăn, và được quyền lấy những thứ như nước tương, chao, muối... đã để sẵn trên kệ cơm.
8. Lấy cơm để vào bát xong đậy nắp bát lại, nắp bát để ngửa, để những thực phẩm ngoài mâm như trái cây, bánh, hộp sữa... trên nắp bát.
9. Đặt bát cơm lên mâm thức ăn cho ngay ngắn, đứng thẳng người xá một xá biết ơn, rồi bưng bát về thất.
+
Vì tập thể khá đông, yêu cầu quý tu sinh lấy cơm nhanh gọn để kịp giờ thọ trai.

=== CÁCH NGỒI ĂN VÀ CÁCH ĂN:
1. Đặt mâm lên bàn hoặc ngồi dưới đất, ngồi bán già hoặc kiết già giữa thất.
2. Chuẩn bị sẵn những đồ dùng như, khăn, dao, muỗng, đũa, nước uống... đầy đủ, để khi đã ngồi xuống ăn không được đứng lên đi tới đi lui, lấy thêm cái này cái kia nữa.
3. Ngồi thẳng lưng, chắp tay lên đọc bài “Ước Nguyện” cúng dường.
4. Sau khi đọc bài “Ước Nguyện” cúng dường xong, ăn ba muỗng cơm trắng và thầm nguyện.
5. Cách thức ăn: quý vị xem quyển Giới Đức Làm Người tập 1, chương 4, trang 156: “Ăn uống phải trang nghiêm tề chỉnh, có 23 giới”.
6. Thọ thực xong, chắp tay đọc bài “Biết Ơn”, rồi xá một xá.
7. Đứng lên cởi áo tràng và thu dẹp, dọn rửa. (Không nên mặc áo tràng để làm những công việc giặt rửa, lao tác...)

[.text-center]
Kính ghi +
Tu viện Chơn Như +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== ƯỚC NGUYỆN TRƯỚC KHI THỌ THỰC

Trước khi thọ thực, người tu sĩ phải ngồi xếp bằng trên ván, giường, ghế hoặc trên mặt đất, dưới bóng cây, trong chòi tranh vách lá, phải đặt bát cơm trước mặt, hai tay chắp lại, lòng thành kính dâng lên tỏ lòng biết ơn chư Phật, tổ tiên, ông bà, cha mẹ nhiều đời nhiều kiếp, và đọc lời ƯỚC NGUYỆN:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.] 
Hôm nay bữa cơm này 
Chúng con xin thành kính 
Nhớ ơn Phật Thích Ca
Tổ tiên và ông bà
Cha mẹ và quyến thuộc 
Anh em cùng bạn hữu
Nội ngoại cùng đôi bên 
Nhiều đời vô lượng kiếp 
Chúng con cũng cúi xin 
Cúng dường khắp pháp giới 
Chúng sanh và tất cả
Hữu tình và vô tình
Ðều được hưởng cơm này 
No lòng như chúng con
Ðể rồi quyết chí tu
Giải trừ tâm ác độc
Tăng trưởng hạnh từ bi 
Thương xót khắp quần sanh 
Thể hiện pháp thiền định 
Ra khỏi nhà sanh tử
Làm chủ đường luân hồi 
Báo đáp bốn trọng ân
Gìn giữ ngôi Tam Bảo
Cửu trụ mãi muôn đời

Sau khi đọc thầm lời Ước Nguyện trước khi thọ thực, kính dâng lên lòng thành kính biết ơn của mình, người tu sĩ ăn ba miếng cơm lạt:

=== TAM ĐỀ:
1. Miếng thứ nhất: Ước nguyện tâm con luôn ngăn ác, diệt ác; ly dục ly ác pháp, diệt ngã xả tâm;
2. Miếng thứ hai: Ước nguyện tâm con sanh thiện, tăng trưởng thiện pháp, luôn sống trong tâm bất động, thanh thản, an lạc, vô sự;
3. Miếng thứ ba: Ước nguyện tất cả chúng sanh đều ly dục, ly ác pháp, sống không làm khổ mình, khổ người.

=== NGŨ QUÁN:
1. Quán xét công ơn người đàn na thí chủ rất nặng, làm ra thực phẩm bằng mồ hôi nước mắt, bao nhiêu công khó khổ để cúng dường.
2. Quán xét giới luật mình có nghiêm chỉnh hay chưa? Nếu còn phạm giới có xứng đáng thọ nhận sự cúng dường đó chưa?
3. Quán xét công đức tu hành ly dục, ly ác pháp của mình có xứng đáng thọ nhận sự cúng dường đó chưa?
4. Quán xét thực phẩm bất tịnh mình có nhàm chán hay chưa? Nếu đã có tâm nhàm chán thì mới xứng đáng thọ dụng của đàn na thí chủ.
5. Quán xét đời sống thiểu dục tri túc, minh hạnh của mình có tròn vẹn hay chưa? Nếu xét thấy đời sống của mình thiểu dục tri túc và oai nghi chánh hạnh đầy đủ, thì xứng đáng thọ dụng của đàn na thí chủ.

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== ƯỚC NGUYỆN SAU KHI THỌ THỰC

Sau khi thọ thực và uống nước xong, người tu sĩ chắp tay lên, thầm đọc lời ước nguyện BIẾT ƠN những đàn na thí chủ đã cúng dường tứ sự nuôi thân cho mình:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.]
Nguyện thọ bữa cơm này 
Chúng con mãi nhớ ơn 
Người nông phu khó khổ 
Kẻ dệt cửi nhọc nhằn 
Giọt mồ hôi nước mắt 
Làm ra của cúng dường 
Người đàn na thí chủ
Vì Phật pháp trường tồn 
Chẳng nề công khó khổ 
Kính ngưỡng cúng dâng lên 
Chúng con nguyện giữ gìn 
Tiết kiệm từng chút một 
Chẳng dám phung phí phạm 
Ngày một bữa nuôi thân 
Chẳng dám ăn phi thời
Vì phi thời phí phạm
Như ăn thịt con mình
Chúng con nguyện hết sức 
Năng nổ siêng tu hành
Giải thoát thân tâm mình 
Ra khỏi nhà sanh tử
Đền đáp ơn chư Phật
Ơn sanh thành dưỡng dục 
Ơn đàn na thí chủ
Chúng con cũng nguyện cho 
Kẻ còn người đã mất
Đều được hưởng Phật pháp 
Tâm ly dục, ly ác
Không làm khổ mình, người.

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== ƯỚC NGUYỆN CỦA TÂN TỲ KHEO

Vị tỳ kheo mới xuất gia tu hành, giới luật chưa thanh tịnh, khi thọ nhận thực phẩm của đàn na thí chủ cúng dường phải
làm gì?

Khi nhận thực phẩm của đàn na thí chủ cúng dường xong, người khất sĩ phải đứng yên lặng ước nguyện:
[.text-center]
[verse, Nam Mô Bổn Sư Thích Ca Mâu Ni Phật.]
Hôm nay con thọ nhận 
Của tín thí cúng dường 
Ước nguyện con tu tập 
Giới hạnh tròn nghiêm túc 
Không hề vi phạm lỗi 
Tâm ly dục, ly ác
Không làm khổ mình, người 
Xứng đáng đệ tử Phật 
Gương sáng cho mọi người 
Thắp lên ngọn đèn pháp 
Chấn hưng lại Phật giáo 
Con xin Phật chứng minh.

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== ĐỘC CƯ

Bắt đầu vào tu pháp môn Ngũ Căn là phải sống độc cư, nên biết ngay người tu được hay không tu được. *Vì có sống ĐỘC CƯ là tu tập được, còn không sống ĐỘC CƯ là tu tập không được.* Ở Tu viện, phần đông tu sĩ và cư sĩ đều rớt ở giai đoạn đầu tu tập phòng hộ NĂM CĂN này.

Người không đủ lòng tin dù có tu tập đúng pháp của Phật thì cũng chỉ tu tập lấy có, thường phá hạnh độc cư, đi nói chuyện người này đến người khác. Những người này hiện thân là Ma Ba Tuần trong Phật giáo, thường đi đến thất người này rồi đến thất người khác làm cho mọi người không ai tu tập được.

Khi thấy những loại Ma Ba Tuần này thì quý thầy, quý cô nên đóng cửa thất không tiếp giao, đừng ở gần, nên tránh xa, tránh xa những người này như tránh xa vi trùng bệnh truyền nhiễm.

Trong chúng chỉ có một con Ma Ba Tuần thì trong chúng đó phải cẩn thận, khi thấy bóng dáng con ma đó thì nên đóng cửa thất cho chặt và ngồi thiền nhiếp tâm bất động để vượt qua loài Ma Quỷ.
[.text-right]
(Trích “Ba Mươi Bảy Phẩm Trợ Đạo”, +
trang 21, 23-24)

[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

<<<

== NHẮC NHỞ TU SINH +
[discrete]
=== Ngày 03-08-2011


Tu viện Chơn Như xin yêu cầu tu sinh hiện đang ở tu tập tại Khu Chuyên tu, cần thực hiện một số điều như sau:

=== I- NỘI QUY:
1. Không trồng cây, hái rau, nấm, trái, quả, v.v...
2. Không cất giữ thức ăn trong thất (đường, muối, sữa, nước tương...).
3. Không cất giữ tiền bạc (phóng dật nhờ vả mua đồ vật linh tinh...).
4. Không dự trữ đồ vật trong thất, ví dụ 2 dép, 2 nón (mũ), xà phòng...
5. Không dùng quạt tay (mất oai nghi chánh hạnh của người tu).
6. Vào Khu Chuyên tu là đã trải qua sự rèn luyện ở Khu Tiếp nhận, nên tránh tình trạng ngồi gục tới gục lui (thiếu tỉnh thức).
7. Không được ngủ trong giờ nghỉ (sáng 5h - 7h, chiều 5h - 7h).
8. Không được ngồi thiền (đó là tư thế của thói quen ức chế từ trước).
9. Không được nhắm mắt trong giờ tu tập (dễ bị rơi vào vô ký).
10. Không ngồi trong góc, bóng tối hoặc quay mặt vô vách (khó kiểm tra).
11. Trong giờ tu tập không nên đi làm công việc khác như: đốt rác, quét sân, lau nhà, giặt đồ, đọc sách, sửa chữa, v.v...
12. Không tiếp duyên nói chuyện phá độc cư, ngoại trừ những người có trách nhiệm quản lý trong Tu viện.
13. Khi gặp khách tham quan hoặc người lạ thì nên tránh duyên, không để người xá chào hoặc xá chào lại.
14. Vào Khu Chuyên tu phải ý thức tự giác, không được gọi điện thoại, viết thư thăm hỏi, ra, vào Tu viện thăm viếng (về thăm gia đình)...
15. Trong thất và xung quanh thất phải vệ sinh sạch sẽ, gọn gàng, ngăn nắp, không được phát sinh bày biện (làm giàn, kệ, chậu, giăng mắc, treo móc...); sống lập hạnh thiểu dục tri túc (BA Y MỘT BÁT).
16. Phơi quần áo phải kín đáo, gọn gàng (đặt giá phơi sau lưng thất).

=== II- CÁCH THỨC TU TẬP:
Tu viện xin nhắc lại: tu sinh nên chuyên cần tu 2 pháp như sau:

1. Tu tập Chánh Niệm Tỉnh Giác. 
2. Tu tập Định Vô Lậu.

*A- Tu tập Chánh Niệm Tỉnh Giác.*

1. Đối với tu sinh cấp I, phải rèn luyện tu tập Tỉnh Thức:

a. Tác Ý khi đi Kinh Hành.
b. Thân Hành Niệm.
[unstyled]
. Mục đích đạt sức Tỉnh Thức trong 3 oai nghi (đi, đứng và ngồi).
+
2. Đối với tu sinh cấp II, phải rèn luyện sức tỉnh giác:

a. Hướng Tâm trong Chánh Niệm (luôn sống trong Hiện Tại).
b. Khắc phục Hôn Trầm, Vô Ký, và phải siêng năng đi Kinh Hành.
[unstyled]
. Mục đích đạt được sức Định Tỉnh trong 4 oai nghi (đi, đứng, ngồi và nằm).

*B- Tu tập Định Vô Lậu (ngồi tự nhiên).*

1. Đối với tu sinh cấp I, tu tập Chánh Kiến, Chánh Tư Duy:

a. Quán về Nhân Quả, Vô Thường, Vô Ngã, Duyên Hợp, Duyên Tan, Thân Bất Tịnh và Thực Phẩm Bất Tịnh.
b. Quán các pháp với từng Tâm Niệm sinh khởi.
[unstyled]
. Mục đích đạt Tri Kiến Giải Thoát, Tâm Vô Lậu, Tâm Bất Động (thấu hiểu như thật nên tâm không còn chướng ngại).
+
2. Đối với tu sinh cấp II, sống với TÂM BẤT ĐỘNG:

a. Sống với Tâm Giải Thoát, Thanh Thản, An Lạc và Vô Sự.
b. Đi vào TỨ NIỆM XỨ (Do sống kéo dài với Tâm Bất Động nên Tâm Thanh Tịnh TỰ QUAY VÔ, hoàn toàn không tu tập một pháp môn nào).
[unstyled]
. Mục đích để VIÊN MÃN TỨ NIỆM XỨ.

Đây là 2 pháp tu căn bản quá rõ ràng rành mạch, để tu sinh tự trắc nghiệm từng giai đoạn đạt hay không đạt, mà tự điều chỉnh lại sự tu tập cho chính mình. Nếu như tu sinh nào ỨC CHẾ hay CĂNG THẲNG rồi sinh bệnh, thì tu sinh ấy đã tu sai pháp của Tu viện, không thực hành đúng theo pháp của Thầy đã dạy. Vì vậy cần nên khắc phục và điều chỉnh cho kịp thời, đúng pháp của Tu viện.

=== XIN LƯU Ý:
Tu sinh cần phải nghe theo người hướng dẫn tu tập và người kiểm tra của từng khu mà Thầy đã giao.

Riêng Khu Chuyên tu bên nam tạm thời chưa có người hướng dẫn, có thể viết thư thưa hỏi Thầy khi gặp trở ngại.

[.text-center]
Kính ghi +
Tu viện Chơn Như +
 +
icon:pagelines[] icon:pagelines[] icon:pagelines[]


== KÍNH GỬI QUÝ TU SINH KHU TIẾP NHẬN!
[discrete]
=== Ngày 07-02-2013

Từ trước đến nay, Tu viện chúng ta lấy Giới luật làm nền tảng tu tập, mà điều cốt lõi chính là ĂN - NGỦ - ĐỘC CƯ. Quý vị đến Tu viện tu tập, trước khi vào thất chúng tôi đã có sinh hoạt một số điều nhỏ nằm trong ĂN - NGỦ - ĐỘC CƯ (mà quý vị thường hay mắc phải). Tuy là nhỏ nhưng nó cũng nói lên được cái tâm của mình có tỉnh thức, có xả được hay không. Dù đã có sinh hoạt trước rồi, nhưng khi vào thất tu tập quý vị vẫn vi phạm. Khi được hỏi vì sao thì quý vị trả lời là không biết, bị quên v.v... Vì vậy chúng tôi xin ghi lại những điều nhỏ này để quý vị lưu ý mà tránh được những lỗi nhỏ nhặt:

_[.underline]#ĂN:#_

1. Khi đi khất thực, phải ôm bát đi từ từ, nhẹ nhàng, nghiêm trang, không được đội khăn, mũ, nón v.v...
2. Đến kệ cơm, nếu có người đang lấy cơm thì chúng ta đứng ra xa để chờ đợi.
3. Đến kệ cơm, lấy mâm theo thứ tự từ dưới lên trên, từ phải sang trái.
4. Xem mâm thức ăn trước để lấy gia vị và lấy cơm vừa đủ ăn (để tránh trường hợp đi khất thực lần thứ 2).
5. Gia vị trên kệ cơm như tương, chao, muối v.v... quý vị lấy tại chỗ, không được mang nguyên chai, lọ v.v... về thất.
6. Có mì gói, cháo gói thì lấy nước nóng tại chỗ, không được mang phích nước nóng về thất.


_[.underline]#NGỦ:#_

1. Luôn giữ gìn giờ giấc nghiêm chỉnh.
2. 2h khuya dậy, phải xếp gọn mùng, mền, chiếu, gối cất vào ngăn tủ.
3. Đến giờ tu không được làm lặt vặt lấn qua 5 - 10 phút (lao tác, tắm giặt, tưới cây, nhổ cỏ v.v... ).
4. Hết giờ tu mới xả nghỉ, không được đi làm sớm 5 - 10 phút (chuẩn bị khất thực, chuẩn bị ngủ v.v...).
5. Trong giờ tu không được phóng dật làm việc lặt vặt.
6. Buổi sáng nằm nghỉ từ 5h đến 6h, không được nghỉ quá giờ.


_[.underline]#ĐỘC CƯ:#_

1. Không được nghe băng, đọc sách.
2. Không ra dấu, ra hiệu, viết thư qua lại. 
3. Không cười hay xá chào khi gặp nhau. 
4. Không lao tác chung.
5. Không hỏi chuyện bất kỳ một người nào ngoại trừ người có trách nhiệm trong khu vực của mình tu tập.
6. Không được đi đến thất của người khác.
7. Không được mở cửa thất trống để lấy vật dụng trong thất.
8. Không được lưu ý nhìn ngó ai hoặc công việc của ai.
9. Phải luôn phòng hộ 6 căn để giữ độc cư cho mình, cho người (mọi người phải luôn giữ khoảng cách nhau 3m).
10. Không cất giữ điện thoại.
[unstyled]
. Kính thưa quý tu sinh!

Thầy đã dạy: “Giữ độc cư thì chúng ta mới ly dục, ly ác pháp được”. Dù quý vị vào đây tu tập một ngày cũng phải giữ cho được Thánh Hạnh này mới xứng đáng là đệ tử của Phật, của Thầy, mới xứng đáng thọ nhận của đàn na thí chủ và quý vị mới cảm nhận được sự GIẢI THOÁT.

Kính mong quý vị hãy cố gắng giữ gìn Giới Luật nghiêm túc để được lợi ích cho mình, cho người, để không phụ công ơn của Thầy.

[cols="^1,^1", frame=none, grid=none]
|===
|Đã duyệt
|Kính ghi

|Thích Mật Hạnh
|Ban Quản Lý TVCN
|===


[.text-center]
icon:pagelines[] icon:pagelines[] icon:pagelines[]

   Đã duyệt                      Kính ghiThích Mật Hạnh Ban Quản Lý TVCN
